### PR TITLE
Check for target dependencies when auto upgrading in codegen

### LINKED ISSUE #2804: Polisher can't find flutter_rust_bridge in target dependencies
### Describe the bug

We have a project with both wasm and Dart compilation targets, therefore `flutter_rust_bridge` is defined in `[target.'cfg(not(target_family = "wasm"))'.dependencies]` section of Cargo.toml.

But when we try to generate Dart bindings, `flutter_rust_bridge_codegen generate` panics with `no entry found for key` error. It happens because `RustUpgrader` checks for version of `flutter_rust_bridge` only in `[dependencies]` section.

The panic cannot be fixed with `--no-auto-upgrade-dependency ` because Upgrader checks version of `flutter_rust_bridge` before checking the flag.

### Steps to reproduce

Move `flutter_rust_bridge` from `[dependencies]` section into `[target.'cfg(not(target_family = "wasm"))'.dependencies]`:

```
- [dependencies]
- flutter_rust_bridge = "=2.11.1"

+ [target.'cfg(not(target_family = "wasm"))'.dependencies]
+ flutter_rust_bridge = "=2.11.1"
```

And then run `flutter_rust_bridge_codegen generate`.

### Logs

```shell
[2025-07-10T16:00:51.227Z ERROR /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/flutter_rust_bridge_codegen-2.11.1/src/library/utils/logs.rs:54] panicked at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/flutter_rust_bridge_codegen-2.11.1/src/library/codegen/polisher/auto_upgrade.rs:63:41:
no entry found for key

thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/flutter_rust_bridge_codegen-2.11.1/src/library/codegen/polisher/auto_upgrade.rs:63:41:
no entry found for key
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: <lib_flutter_rust_bridge_codegen::library::codegen::polisher::auto_upgrade::RustUpgrader as lib_flutter_rust_bridge_codegen::library::codegen::polisher::auto_upgrade::Upgrader>::check
   4: lib_flutter_rust_bridge_codegen::library::codegen::polisher::auto_upgrade::execute
   5: lib_flutter_rust_bridge_codegen::library::codegen::polisher::polish
   6: lib_flutter_rust_bridge_codegen::library::codegen::generate_once
   7: lib_flutter_rust_bridge_codegen::library::codegen::controller::run
   8: lib_flutter_rust_bridge_codegen::library::codegen::generate
   9: flutter_rust_bridge_codegen::main
```

### Expected behavior

It would be nice if `flutter_rust_bridge_codegen generate` will check for dependency in targets or just won't panic and proceed with a warning.

### Generated binding code

```shell

```

### OS

Ubuntu 22.04.5 LTS

### Version of `flutter_rust_bridge_codegen`

2.11.1

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.32.5, on Ubuntu 22.04.5 LTS 5.15.0-131-generic, locale en_US.UTF-8) [59ms]
    • Flutter version 3.32.5 on channel stable at /root/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fcf2c11572 (2 weeks ago), 2025-06-24 11:44:07 -0700
    • Engine revision dd93de6fb1
    • Dart version 3.8.1
    • DevTools version 2.45.1

[✗] Android toolchain - develop for Android devices [50ms]
    • Android SDK at /root/Android/Sdk
    ✗ cmdline-tools component is missing.
      Try installing or updating Android Studio.
      Alternatively, download the tools from https://developer.android.com/studio#command-line-tools-only and make sure to set the ANDROID_HOME environment
      variable.
      See https://developer.android.com/studio/command-line for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome) [24ms]
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop [208ms]
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 1.8.0
    ! Unable to access driver information using 'eglinfo'.
      It is likely available from your distribution (e.g.: apt install mesa-utils)

[!] Android Studio (not installed) [19ms]
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] Connected device (1 available) [52ms]
    • Linux (desktop) • linux • linux-x64 • Ubuntu 22.04.5 LTS 5.15.0-131-generic

[✓] Network resources [899ms]
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

### Version of `clang++`

14.0.0-1ubuntu1.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by turtletongue**
## Changes

Fixes #2804

### CODE REVIEW

File: frb_codegen/src/library/codegen/polisher/auto_upgrade.rs [hunk 1]
```diff
@@ -14,33 +15,49 @@ pub(super) fn execute(
...
 }
 
-struct DartUpgrader;
+struct DartUpgrader<'a> {
+    repository: DartRepository,
+    base_dir: &'a Path,
+}
+
+impl<'a> DartUpgrader<'a> {
+    fn build(base_dir: &'a Path) -> Result<Self> {
```
Comment (fzyzcjy) [inline frb_codegen/src/library/codegen/polisher/auto_upgrade.rs]: nit: what about `fn new`

(same for RustUpgrader)

File: frb_codegen/src/library/codegen/polisher/auto_upgrade.rs [hunk 2]
```diff
@@ -49,26 +66,63 @@ impl Upgrader for DartUpgrader {
...
+        let mut args = vec![concat!("flutter_rust_bridge@=", env!("CARGO_PKG_VERSION"))];
+
+        let target = self
+            .target_name
+            .as_ref()
+            .map(|name| format!("--target={name}"));
+
+        if let Some(target) = &target {
+            args.push(target);
+        }
```
Comment (fzyzcjy) [inline frb_codegen/src/library/codegen/polisher/auto_upgrade.rs:130]: nit


```suggestion
        if let Some(target_name) = &self.target_name {
            args.push(format!(...));
        }
```

File: frb_codegen/src/library/codegen/polisher/auto_upgrade.rs [hunk 3]
```diff
@@ -49,26 +66,63 @@ impl Upgrader for DartUpgrader {
...
+            .map(|dep| (None, dep.clone()))
+            .into_iter()
+            .chain(manifest.target.iter().filter_map(|(name, target)| {
+                target
+                    .dependencies
+                    .get("flutter_rust_bridge")
+                    .map(|dep| (Some(name.to_owned()), dep.clone()))
+            }))
+            .next()
+            .ok_or_else(|| anyhow!("flutter_rust_bridge not found in Cargo.toml dependencies"))?;
```
Comment (fzyzcjy) [inline frb_codegen/src/library/codegen/polisher/auto_upgrade.rs]: nit: what about extract to a fn like

```
fn get_dependency(manifest, package_name: &str)
```

and call like

```
let (target_name, dependency) = get_dependency(manifest, "flutter_rust_bridge")
```

File: frb_codegen/src/library/codegen/polisher/auto_upgrade.rs (hunk 2 above)
Comment (turtletongue) [reply frb_codegen/src/library/codegen/polisher/auto_upgrade.rs:130]: `args` here is a vector of `&str` so just pushing format!(...) won't work because it returns String. I've used target binding to increase lifetime of format!(...) result

Comment (fzyzcjy) [reply frb_codegen/src/library/codegen/polisher/auto_upgrade.rs:130]: oh i see

**Comment by fzyzcjy** [comment]
before merging, could you please check whether this runs well on your case (which fails before)?

**Comment by turtletongue** [comment]
Yes, I checked and it works without any errors

**Comment by fzyzcjy** [comment]
@all-contributors please add turtletongue for code
