### PR TITLE
Fix #1462 (Generated Rust code of `Result<RustOpaque<...>>` is incorrect)

### LINKED ISSUE #1462: [Bug] Generated Rust code of `Result<RustOpaque<...>>` is incorrect
### Describe the bug

When using anyhow::Result with an opaque type like this

```rust
use flutter_rust_bridge::frb;

#[frb(opaque)]
pub struct T(i32);

impl T {
    pub fn new() -> anyhow::Result<T> {
        Ok(T(0))
    }
}
```

the generated code does not compile.
```
error[E0308]: mismatched types
  --> src/frb_generated.rs:45:38
   |
45 |                   transform_result_dco((move || {
   |  _________________--------------------_^
   | |                 |
   | |                 arguments to this function are incorrect
46 | |                     flutter_rust_bridge::for_generated::rust_auto_opaque_encode(
47 | |                         crate::api::simple::T::new(),
48 | |                     )
49 | |                 })())
   | |____________________^ expected `Result<_, _>`, found `RustOpaque<RwLock<Result<T, Error>>>`
   |
   = note: expected enum `Result<_, _>`
            found struct `RustOpaque<RwLock<Result<simple::T, anyhow::Error>>>`
note: function defined here
  --> /home/trobanga/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge-2.0.0-dev.2/src/codec/dco.rs:60:8
   |
60 | pub fn transform_result_dco<T, T2, E>(
   |        ^^^^^^^^^^^^^^^^^^^^
help: try wrapping the expression in a variant of `Result`
   |
45 ~                 transform_result_dco(Ok((move || {
46 |                     flutter_rust_bridge::for_generated::rust_auto_opaque_encode(
47 |                         crate::api::simple::T::new(),
48 |                     )
49 ~                 })()))
   |
45 ~                 transform_result_dco(Err((move || {
46 |                     flutter_rust_bridge::for_generated::rust_auto_opaque_encode(
47 |                         crate::api::simple::T::new(),
48 |                     )
49 ~                 })()))
   |
```

The generated code is:
```rust
fn wire_T_new_impl(port_: flutter_rust_bridge::for_generated::MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "T_new",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| {
                transform_result_dco((move || {
                    flutter_rust_bridge::for_generated::rust_auto_opaque_encode(
                        crate::api::simple::T::new(),
                    )
                })())
            }
        },
    )
}
```

but it should be:
```rust
fn wire_T_new_impl(port_: flutter_rust_bridge::for_generated::MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "T_new",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| {
                transform_result_dco(Ok::<
                    flutter_rust_bridge::RustOpaque<
                        std::sync::RwLock<
                            std::result::Result<crate::api::simple::T, anyhow::Error>,
                        >,
                    >,
                    anyhow::Error,
                >((move || {
                    flutter_rust_bridge::for_generated::rust_auto_opaque_encode(
                        crate::api::simple::T::new(),
                    )
                })()))
            }
        },
    )
}
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
probably not relevant
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Generated binding code

_No response_

### OS

Arch Linux

### Version of `flutter_rust_bridge_codegen`

2.0.0-dev.2

### Flutter info

_No response_

### Version of `clang++`

16

### Version of `ffigen`

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by trobanga**
## Changes
Fix #1462

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [x] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api/whatever.rs` and `test/api/whatever_test.dart`.
- [x] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [x] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- [ ] CI is passing. (Operations are reproducible using corresponding `./frb_internal something` commands shown in CI.)

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by trobanga** [comment]
The test that is failing...could it be that I have to run `./frb_internal precommit --mode slow` or `generate-internal` to generate the SSE related code? Well, that fails for me with /bin/sh: line 1: all-contributors: command not found.

**Comment by fzyzcjy** [comment]
Just run `./frb_internal generate-internal-frb-example-pure-dart` locally. (I should update the command though)

**Comment by trobanga** [comment]
Weird things happen on my machine, if I run that...

**Comment by fzyzcjy** [comment]
May I know what is that? Then it looks like bug in the script.

Btw, you can also copy-paste the git diff shown in the CI and run `git apply` patch locally to fix it.

**Comment by trobanga** [comment]
The script runs but bool are replaced with int in multi_package.dart.
```
-      bool Function(int, ffi.Pointer<Dart_CObject>)>();
+      int Function(int, ffi.Pointer<Dart_CObject>)>();
```
It could be related to these  #1375 and #1421 because to generate the code I have to add `llvm_compiler_opts: -I/usr/lib/clang/16/include` to flutter_rust_bridge.yaml

**Comment by trobanga** [comment]
and it seems  `NonCloneSimpleTwinSse.newWithResult` is not generated.

**Comment by trobanga** [comment]
Maybe multi_package.dart was generated when I tried `./frb_internal precommit --mode slow` and I accidentally commited.

**Comment by fzyzcjy** [comment]
Hmm, feel free to create a separate issue, since this looks like a bug!

**Comment by trobanga** [comment]
will do

**Comment by fzyzcjy** [comment]
Oops, I realize you are saying multi_package.dart, so no need to create issue - that is not user facing.

**Comment by fzyzcjy** [comment]
> Btw, you can also copy-paste the git diff shown in the CI and run git apply patch locally to fix it.

Maybe just copy-paste everything that CI is unhappy to make it happy...

> and it seems NonCloneSimpleTwinSse.newWithResult is not generated.

This is a problem. What about `./frb_internal generate-run-frb-codegen-command-generate --package frb_example/pure_dart` (which `precommit` actually calls)

**Comment by trobanga** [comment]
ok, I thought you meant that NonCloneSimpleTwinSse.newWithResult is not generated.

**Comment by trobanga** [comment]
ah ok, that command did generate NonCloneSimpleTwinSse.newWithResult

**Comment by trobanga** [comment]
Ok, I guess I should run  `./frb_internal precommit --mode fast` more often 😬

**Comment by trobanga** [comment]
The tests for sync sse were autogenerated. Is it known that the postfixes e.g. TwinSse was missing?

**Comment by fzyzcjy** [comment]
> Is it known that the postfixes e.g. TwinSse was missing?

Oops, I should have updated doc: Instead of `new_with_result`, write `new_with_result_twin_normal`

**Comment by fzyzcjy** [comment]
I see, that code is a bit wrong. Maybe this instead:

```
#[cfg(test)]
mod tests {
    #[cfg(not(target_family = "wasm"))]
    #[test]
    fn test_zero_copy_buffer() {
        use crate::misc::into_into_dart::IntoIntoDart;
        let raw: allo_isolate::ZeroCopyBuffer<Vec<u8>> = allo_isolate::ZeroCopyBuffer(vec![10]);
        assert_eq!(raw.into_into_dart().0, vec![10]);
    }
}
```

image

**Comment by trobanga** [comment]
yes, I was thinking the same.

**Comment by trobanga** [comment]
Should I make a new PR for that or is here ok?

**Comment by trobanga** [comment]
Hm, if I run `./frb_internal generate-run-frb-codegen-command-generate --package frb_example/pure_dart` in pure_dart/.../rust_auto_opaque.dart the constructor name newWithResultTwinNormal is changed to newWithResult. Any idea what could cause this?

**Comment by trobanga** [comment]
ok, got it

**Comment by trobanga** [comment]
Here is one I don't understand: `./frb_internal precommit --mode fast` changes a test in `frb_rust/src/dart_opaque/boxes/thread_box.rs` from 
```
    #[test]
    fn test_thread_box_should_panic_and_leak_when_access_and_drop_on_another_thread() {
        let b = ThreadBox::new(42);
        thread::spawn(move || {
            assert_panics!((move || {
                let _inner: &i32 = b.as_ref();
            })());
        })
        .join()
        .unwrap();
    }
```
to
```
    #[test]
    fn test_thread_box_should_panic_and_leak_when_access_and_drop_on_another_thread() {
        let b = ThreadBox::new(42);
        thread::spawn(move || {
            assert_panics!({
                let _inner: &i32 = b.as_ref();
            });
        })
        .join()
        .unwrap();
    }
```

**Comment by fzyzcjy** [comment]
> 
Should I make a new PR for that or is here ok?



Not a big problem to put it here, as long as this one is going to be merged (I think so!)

**Comment by fzyzcjy** [comment]
> Here is one I don't understand: ./frb_internal precommit --mode fast changes a test in frb_rust/src/dart_opaque/boxes/thread_box.rs from

IIRC we need to ensure that is not auto changed (by adding some `#[allow(some-thing-here)]`), otherwise we are not testing the access_and_drop scenario

**Comment by trobanga** [comment]
It's  #[allow(clippy::redundant_closure_call)]

File: frb_codegen/src/library/codegen/generator/wire/rust/spec_generator/misc/wire_func.rs [hunk 1]
```diff
@@ -238,11 +242,15 @@ fn generate_code_closure(
     code_call_inner_func_result: &str,
 ) -> String {
     let codec = (func.codec_mode_pack.rust2dart.to_string()).to_case(Case::Snake);
+    let mut maybe_result = "".to_string();
+    if matches!(&func.output, IrType::RustAutoOpaque(_)) && func.fallible() {
+        maybe_result = "-> Result::<_,anyhow::Error>".to_string()
+    };
```
Comment (fzyzcjy) [inline frb_codegen/src/library/codegen/generator/wire/rust/spec_generator/misc/wire_func.rs:248]: nit: what about if-else, s.t. it can be non-mut

let maybe_result = if ... { "-> Result..." } else {""};

**Review by fzyzcjy — APPROVED** [review]
Good job! Only a nit and ready to merge
