### PR TITLE
Fix `Optional<DateTime>`

### LINKED ISSUE #1077: [Bug] Optional Datetime doesn’t work in structs
### Describe the bug

The generated function:
```dart
  DateTime _wire2api_box_autoadd_Chrono_Naive(dynamic raw) {
    return raw as DateTime;
  }
```
throws a runtime error. It has to be:
```dart
  DateTime _wire2api_box_autoadd_Chrono_Naive(dynamic raw) {
    return DateTime.fromMicrosecondsSinceEpoch(_wire2api_i64(raw));
  }
```

this seems not to work either:
```dart
 DateTime _wire2api_box_autoadd_Chrono_Utc(dynamic raw) {
    return wire2apiTimestamp(ts: raw as int, isUtc: false);
  }
```
### Codegen logs with `RUST_LOG=debug` environment variable

```shell
-
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Generated binding code

_No response_

### OS

_No response_

### Version of `flutter_rust_bridge_codegen`

_No response_

### Flutter info

_No response_

### Version of `clang++`

_No response_

### Version of `ffigen`

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexthe2**
## Changes

Close #1077 

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [x] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- [x] The code generator is run and the code is formatted (via `just precommit`).
- [x] If this PR adds/changes features, documentations (in the `./book` folder) are updated.
- [x] CI is passing.

## Remark for PR creator

- Justfile is a task runner for the command line interface that allows you to run shell commands from a file named `justfile` in your project directory. You can use Justfile after [installing it](https://github.com/casey/just). Note that commands written in `justfile` of this repository are expected to be run in `bash`, not `cmd` or `powershell`. Running `just ...` commands in `cmd` or `powershell` will produce errors as the syntax is not compatible. On Windows, you can use `git bash` if you have Git installed.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by alexthe2** [comment]
@Desdaemon do you mind taking a look at the web tests, I can’t read them, (aka it doesnt make sense to me)

**Comment by Desdaemon** [comment]
> TypeError: Instance of 'BigInt': type 'BigInt' is not a subtype of type 'int'

You'll need to convert a BigInt to int first, IIRC `castInt` should be one of the ways to do it.

**Comment by alexthe2** [comment]
> > TypeError: Instance of 'BigInt': type 'BigInt' is not a subtype of type 'int'
> 
> You'll need to convert a BigInt to int first, IIRC `castInt` should be one of the ways to do it.

you don’t by chance know where it is right?

**Comment by Desdaemon** [comment]
https://github.com/fzyzcjy/flutter_rust_bridge/blob/ee333662d6fe0b93b1fb5b5a477793a230390990/frb_dart/lib/src/ffi/stub.dart#L65

It should already be in scope when you import the main library.

**Comment by fzyzcjy** [comment]
Nice :) Feel free to ping me when CI is green

**Comment by alexthe2** [comment]
here we go @fzyzcjy 🏓

**Comment by alexthe2** [comment]
also can I get a code emoji 🙃

**Comment by fzyzcjy** [comment]
> also can I get a code emoji 🙃

Definitely! I did not realize I forgot to do so

File: frb_codegen/src/generator/dart/ty_boxed.rs [hunk 1]
```diff
@@ -80,6 +83,8 @@ impl TypeDartGeneratorTrait for TypeBoxedGenerator<'_> {
             | Delegate(IrTypeDelegate::Array(_) | IrTypeDelegate::PrimitiveEnum { .. }) => {
                 format!("return _wire2api_{}(raw);", self.ir.inner.safe_ident())
             }
+            #[cfg(feature = "chrono")]
+            Delegate(IrTypeDelegate::Time(time)) => gen_wire2api_chrono(time),
```
Comment (fzyzcjy) [inline frb_codegen/src/generator/dart/ty_boxed.rs:87]: uber-nit: how is its friends? (e.g. date/datetime)

seems I have asked this question recently, not sure whether to you or someone else? If you have explained just point me to your old reply is enough ;)

File: frb_example/pure_dart/dart/lib/main.dart [hunk 2]
```diff
@@ -677,6 +677,14 @@ void main(List<String> args) async {
       final resp = await api.duration(d: duration);
       expect(resp.inHours, duration.inHours);
     });
+
+    test('Combined Chrono types', () async {
+      final test = await api.testChrono();
+      expect(castInt(test.dt!.millisecondsSinceEpoch), castInt(1631297333000));
+      expect(castInt(test.dt2!.millisecondsSinceEpoch), castInt(1631297333000));
+      expect(test.du, Duration(hours: 4));
```
Comment (fzyzcjy) [inline frb_example/pure_dart/dart/lib/main.dart:685]: uber-nit: would be great to add one more test, about is accuracy. For example, if your design makes it milliseconds accuracy, then test something like "123ms" and see it is correct (instead of a truncated "120ms" etc)

Also good to test the range. For example, if theoretically it can handle 100yr then test it

Anyway this is optional, and only do it if it is convenient :)

**Review by fzyzcjy — COMMENTED** [review]
Ready to merge! Only nits

File: frb_codegen/src/generator/dart/mod.rs [hunk 3]
```diff
@@ -566,6 +566,16 @@ fn generate_opaque_func(ty: &IrType) -> Acc<String> {
     }
 }
 
+#[cfg(feature = "chrono")]
+fn gen_wire2api_chrono(chrono_type: &IrTypeTime) -> String {
+    match chrono_type {
+        IrTypeTime::Local => "return _wire2api_Chrono_Local(raw);".to_string(),
+        IrTypeTime::Utc => "return _wire2api_Chrono_Utc(raw);".to_string(),
+        IrTypeTime::Naive => "return _wire2api_Chrono_Naive(raw);".to_string(),
+        IrTypeTime::Duration => "return _wire2api_Chrono_Duration(raw);".to_string(),
```
[the remark this answers is not in the document]
Comment (alexthe2) [reply frb_codegen/src/generator/dart/mod.rs:575]: fair, this looks nice, I’ll add it

File: frb_codegen/src/generator/dart/ty_boxed.rs (hunk 1 above)
Comment (alexthe2) [reply frb_codegen/src/generator/dart/ty_boxed.rs:87]: NaiveDate and Date and NaiveTime and Time you mean? They’re not yet supported

Comment (alexthe2) [reply frb_codegen/src/generator/dart/ty_boxed.rs:87]: I can create a Feature Issue for this and fix it at one point

Comment (fzyzcjy) [reply frb_codegen/src/generator/dart/ty_boxed.rs:87]: I see. Get it!

**Comment by alexthe2** [comment]
@fzyzcjy 🏓

**Review by fzyzcjy — APPROVED** [review]

**Comment by fzyzcjy** [comment]
Good job!
