### PR TITLE
Fix bug with conflicting names in enum name and variant

### LINKED ISSUE #406: [Bug]  Variant Enum in stream
### Describe the bug

Hi :) 
now I try to adding a  rust variant enum like in the example in the guide and I get this while using the generator 

when doing 
```
pub enum KitchenSink {
    Empty,
    Primitives {
        /// Dart field comment
        int32: i32,
        float64: f64,
        boolean: bool,
    },

    Buffer(ZeroCopyBuffer<Vec<u8>>),
}
pub struct Msg {
    pub id: String,
    pub test: KitchenSink,
}

pub fn message_handler(sink: StreamSink<Msg>) -> anyhow::Result<()>{Ok(())}
```

if this is expected please close this :) 

### Codegen logs with `RUST_LOG=debug` env variable

```shell
[2022-04-20T15:47:54Z WARN  flutter_rust_bridge_codegen::commands] command="powershell" "-noprofile" "-c" "cd \"C:\\Users\\me\\projects\\rust\\project\"; dart run build_runner build --delete-conflicting-outputs" stdout= stderr=Could not find a file named "pubspec.yaml" in "C:\Users\me\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_rust_bridge-1.25.0".
    #0      new Pubspec.load (package:pub/src/pubspec.dart:288:7)
    #1      new Package.load (package:pub/src/package.dart:149:27)
    #2      SystemCache.load (package:pub/src/system_cache.dart:113:20)
    #3      Entrypoint._createPackageGraph (package:pub/src/entrypoint.dart:112:63)
    #4      Entrypoint.packageGraph (package:pub/src/entrypoint.dart:107:54)
    #5      getExecutableForCommand (package:pub/src/executable.dart:338:19)
    #6      RunCommand.run (package:dartdev/src/commands/run.dart:232:32)
    #7      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
    #8      DartdevRunner.runCommand (package:dartdev/dartdev.dart:232:30)
    #9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
    #10     new Future.sync (dart:async/future.dart:296:31)
    #11     CommandRunner.run (package:args/command_runner.dart:119:14)
    #12     runDartdev (package:dartdev/dartdev.dart:67:29)
    #13     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
    #14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:32)
    #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)


[2022-04-20T15:47:54Z ERROR flutter_rust_bridge_codegen::commands] Failed to run build_runner for C:\Users\me\projects\rust\project:
[2022-04-20T15:47:56Z INFO  flutter_rust_bridge_codegen] Success! Now go and use it :)
```

and I get errors like
lib/bridge_generated.dart(99,14): error GB1B8BC88: Method not found: 'Buffer' 
etc when flutter run

### PR DESCRIPTION
**Pull request by Roms1383**
Fixes #406

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [x] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- [x] The code generator has been run, and code changes are commited. (Otherwise, CI will fail.)
- [ ] If this PR adds/changes features, documentations (in the `./book` folder) are updated.
- [x] CI is passing.

### CODE REVIEW

**Comment by Roms1383** [comment]
Ok so far I got the generator generates files that compile, but somehow I broke the tests :boom: :boom: :boom: 😅 
I definitely could use some help here ! ^^

---

Also, as you will see from regenerated files, the naming might not be to your liking. What I came up here is to rename the enum's variants generated classes for example.
So now they are generated in the form **enum_name**`_`**variant_name**`_Variant`.
For example this:
```rust
#[derive(Debug, Clone)]
#[frb(freezed)]
pub enum Speed {
    Unknown,
    GPS(f64),
}
```
Will generate e.g. a class like `Speed_Unknown_Variant` and `Speed_GPS_Variant`.

:warning: Please note that I only modified the generated classes / variables / etc only where necessary, leaving all the rest of the code untouched.

---

:microscope: I initially generated git patches files to investigate (and the error with conflicting names becomes quite apparent) but I can't join them with *.patch extension, so I'm gonna rename them as *.txt.

[conflicting_sample.enum_variant_matches_another_enum_name.txt](https://github.com/fzyzcjy/flutter_rust_bridge/files/9229238/conflicting_sample.enum_variant_matches_another_enum_name.txt)
[conflicting_sample.enum_variant_matches_another_enum_variant.txt](https://github.com/fzyzcjy/flutter_rust_bridge/files/9229239/conflicting_sample.enum_variant_matches_another_enum_variant.txt)
[working_sample.txt](https://github.com/fzyzcjy/flutter_rust_bridge/files/9229240/working_sample.txt)

**Comment by fzyzcjy** [comment]
> Will generate e.g. a class like Speed_Unknown_Variant and Speed_GPS_Variant.

I am thinking about this naming thing. Shall we call it `SpeedUnknown`, `SpeedGPS` etc, *unconditionally* (i.e. always name like that)? I feel it a bit more like `Speed::Unknown`. And moreover, in `freezed`, it is not uncommon to see namings like this.

Since the great enhanced enum feature is impl by desdaemon, /cc @Desdaemon what do you think?

**Comment by fzyzcjy** [comment]
> but somehow I broke the tests 

CI looks good so far :)

Anyway I will wait until this PR is marked as ready for review and then review it.

**Comment by Roms1383** [comment]
> CI looks good so far :)

hey yeah, I was suprised because on my machine `just test-pure` fails (to load dynamic library) :)
<details><summary>click to see error details</summary>

```sh
cd frb_example/pure_dart/dart && dart pub get && dart lib/main.dart ../rust/target/debug/libflutter_rust_bridge_example.dylib
Resolving dependencies... (1.2s)
Got dependencies!
flutter_rust_bridge example program start (dylibPath=../rust/target/debug/libflutter_rust_bridge_example.dylib)
construct api
Unhandled exception:
Invalid argument(s): Failed to load dynamic library '../rust/target/debug/libflutter_rust_bridge_example.dylib': dlopen(../rust/target/debug/libflutter_rust_bridge_example.dylib, 0x0001): tried: '/opt/homebrew/Cellar/dart/2.17.6/libexec/bin/./../rust/target/debug/libflutter_rust_bridge_example.dylib' (no such file), '/opt/homebrew/Cellar/dart/2.17.6/libexec/bin/../../../../rust/target/debug/libflutter_rust_bridge_example.dylib' (no such file), '/opt/homebrew/Cellar/dart/2.17.6/libexec/bin/Frameworks/../rust/target/debug/libflutter_rust_bridge_example.dylib' (no such file), '/opt/homebrew/Cellar/dart/2.17.6/libexec/bin/./../rust/target/debug/libflutter_rust_bridge_example.dylib' (no such file), '/opt/homebrew/Cellar/dart/2.17.6/libexec/bin/../../../../rust/target/debug/libflutter_rust_bridge_example.dylib' (no such file), '/opt/homebrew/Cellar/dart/2.17.6/libexec/bin/Frameworks/../rust/target/debug/libflutter_rust_bridge_example.dylib' (no such file), '../rust/target/debug/libflutter_rust_bridge_example.dylib' (relative path not allowed in hardened program)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      main (package:flutter_rust_bridge_example/main.dart:12:32)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
error: Recipe `test-pure` failed on line 46 with exit code 255
```

</details>

**Comment by Roms1383** [comment]
What is weird regarding the failure at running `just test-pure` locally is that it cannot find the compiled `libflutter_rust_bridge_example.dylib` inside `../rust/target/debug/` but I re-ran `cargo build` already, checked its presence and still get the same error.

**Comment by fzyzcjy** [comment]
> "relative path not allowed in hardened program"

is that some cause?

Anyway, as long as CI is happy we are surely happy :)

**Comment by Roms1383** [comment]
ok @fzyzcjy waiting for your review :)

**Comment by fzyzcjy** [comment]
I will review it tomorrow morning (~8hr from now) :)

File: frb_example/pure_dart/rust/src/api.rs [hunk 1]
```diff
@@ -725,3 +725,36 @@ impl ConcatenateWith {
...
+    match api {
+        API::Speed(v) => {
+            println!("speed changed: {:#?}", *v);
+        }
+        API::KilometerPoint(v) => {
+            println!("kilometer point changed: {:#?}", *v);
+        }
+    };
+    Ok(())
+}
```
Comment (fzyzcjy) [inline frb_example/pure_dart/rust/src/api.rs:760]: I am not sure, shall we use names that clearly describe what we are testing, instead of these. Especially the "API"...

File: frb_example/pure_dart/dart/lib/main.dart [hunk 2]
```diff
@@ -256,28 +256,28 @@ void main(List<String> args) async {
   });
 
   test('dart call handleEnumStruct', () async {
-    expect(await api.handleEnumStruct(val: Empty()), Empty());
+    expect(await api.handleEnumStruct(val: KitchenSink_Empty_Variant()), KitchenSink_Empty_Variant());
```
Comment (fzyzcjy) [inline frb_example/pure_dart/dart/lib/main.dart:259]: As discussed before, shall we use `KitchinSink_Empty` instead of `KitchenSink_Empty_Variant`

File: frb_example/pure_dart/dart/lib/main.dart [hunk 3]
```diff
@@ -323,8 +323,8 @@ void main(List<String> args) async {
 
   test('dart call getMessage()', () async {
     var message = await api.getMessage();
-    expect(message is RenderPixel, true);
-    message as RenderPixel;
+    expect(message is ApplicationMessage_RenderPixel_Variant, true);
+    message as ApplicationMessage_RenderPixel_Variant;
```
Comment (fzyzcjy) [inline frb_example/pure_dart/dart/lib/main.dart:327]: Please add some (very simple) tests calling the new functions that you have generated :)

Since we want to ensure names are correct, we may need:

```
expect(TheClassThatYouAreInterested.toString(), 'TheClassThatYouAreInterested');

**Review by fzyzcjy — COMMENTED** [review]
Good job except for a few minor changes :)

File: frb_example/pure_dart/dart/lib/main.dart (hunk 2 above)
Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:259]: I agree we can come up with a better naming around structs generated for enums variants.

The issue with name like e.g. `KitchenSink_Empty` is that it already conflicts with pre-existing generated code.

```bash
➜  flutter_rust_bridge git:(fix/enum-variant-naming-conflicts) ✗ just test-pure                
cd frb_example/pure_dart/rust && cargo b
   Compiling flutter_rust_bridge_example_single_block_test v1.0.0 (/Users/romain/Development/contributions/flutter_rust_bridge/frb_example/pure_dart/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 0.82s
cd frb_example/pure_dart/dart && dart pub get && dart lib/main.dart ../rust/target/debug/libflutter_rust_bridge_example.dylib
Resolving dependencies... (1.2s)
Got dependencies!
lib/bridge_generated.freezed.dart:200:16: Error: 'API_Speed' is already declared in this scope.
abstract class API_Speed implements API {
               ^^^^^^^^^
lib/bridge_generated.dart:4292:7: Context: Previous declaration of 'API_Speed'.
class API_Speed extends ffi.Struct {
      ^^^^^^^^^
lib/bridge_generated.freezed.dart:338:16: Error: 'API_KilometerPoint' is already declared in this scope.
abstract class API_KilometerPoint implements API {
               ^^^^^^^^^^^^^^^^^^
lib/bridge_generated.dart:4316:7: Context: Previous declaration of 'API_KilometerPoint'.
class API_KilometerPoint extends ffi.Struct {
      ^^^^^^^^^^^^^^^^^^
lib/bridge_generated.freezed.dart:960:16: Error: 'KilometerPoint_Unknown' is already declared in this scope.
abstract class KilometerPoint_Unknown implements KilometerPoint {
               ^^^^^^^^^^^^^^^^^^^^^^
lib/bridge_generated.dart:4296:7: Context: Previous declaration of 'KilometerPoint_Unknown'.
class KilometerPoint_Unknown extends ffi.Opaque {}
      ^^^^^^^^^^^^^^^^^^^^^^
lib/bridge_generated.freezed.dart:1085:16: Error: 'KilometerPoint_SNCF' is already declared in this scope.
abstract class KilometerPoint_SNCF implements KilometerPoint {
               ^^^^^^^^^^^^^^^^^^^
lib/bridge_generated.dart:4298:7: Context: Previous declaration of 'KilometerPoint_SNCF'.
class KilometerPoint_SNCF extends ffi.Struct {
      ^^^^^^^^^^^^^^^^^^^
lib/bridge_generated.freezed.dart:1294:16: Error: 'KitchenSink_Empty' is already declared in this scope.
abstract class KitchenSink_Empty implements KitchenSink {
               ^^^^^^^^^^^^^^^^^
lib/bridge_generated.dart:4177:7: Context: Previous declaration of 'KitchenSink_Empty'.
class KitchenSink_Empty extends ffi.Opaque {}
      ^^^^^^^^^^^^^^^^^
error: Recipe `test-pure` failed on line 46 with exit code 254
```

Any other convention in mind ? @fzyzcjy

File: frb_example/pure_dart/dart/lib/main.dart (hunk 3 above)
Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:327]: Ok I made it up from previous tests in 5fe576edf13ec5c187ca3ee0041c21c253849d5d

File: frb_example/pure_dart/rust/src/api.rs (hunk 1 above)
Comment (Roms1383) [reply frb_example/pure_dart/rust/src/api.rs]: Renamed in 04c39675717bb02c7183e3f4ee05738fde578fb8 : let me know if it's ok.

File: frb_example/pure_dart/dart/lib/main.dart (hunk 2 above)
Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:259]: Ah that sounds like another problem. The https://github.com/fzyzcjy/flutter_rust_bridge/blob/386a20f1c70a4ac76ce78b129f0f8a35ec39daff/frb_example/pure_dart/dart/lib/bridge_generated.dart#L4292 "API_Speed" should have been "wire_API_speed" imho, since by convention, all those are wire structs and should prefix like that.

/cc @Desdaemon  who implemented the great enhanced enum feature

File: frb_example/pure_dart/rust/src/api.rs (hunk 1 above)
Comment (fzyzcjy) [reply frb_example/pure_dart/rust/src/api.rs]: Looks better :)

File: frb_example/pure_dart/dart/lib/main.dart (hunk 3 above)
Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:327]: Tests like 

`expect(Speed_GPS_Variant.toString(), 'Speed_GPS_Variant');`

may be helpful to ensure the names are what we expect

File: frb_example/pure_dart/dart/lib/main.dart (hunk 2 above)
Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:259]: Oh my latest commit renamed the enums ... :man_facepalming: sorry it's gonna make review more complicated here.

File: frb_example/pure_dart/dart/lib/main.dart (hunk 3 above)
Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:327]: > expect(Speed_GPS_Variant.toString(), 'Speed_GPS_Variant');

I haven't committed yet since the test doesn't pass.
It fails with :
```dart
expect(Speed_GPS_Variant.toString(), 'Speed_GPS_Variant'); // ❌
// The method 'toString' isn't defined for the type 'Speed_GPS_Variant'.
// Try correcting the name to the name of an existing method, or defining a method named 'toString'.
```
But it passes with :
```dart
expect(Speed_Unknown_Variant().toString(), 'Speed.unknown()'); // ✅
expect(Speed_GPS_Variant(0.0).toString(), 'Speed.gps(field0: 0.0)'); // ✅
```

Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:327]: This works:

```dart
(Speed_GPS_Variant as Type).toString()

Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:327]: done in 4ada517f9f2db55219e9156c94a6d7e01bd999cb

p.s: I removed `as Type`
<details><summary>because Dart warns about it</summary>

Screen Shot 2565-08-02 at 10 51 52

</details>

File: frb_example/pure_dart/dart/lib/main.dart (hunk 2 above)
Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:259]: I don't mind doing any change, just waiting for your recommendations @fzyzcjy @Desdaemon

Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:259]: Personally I suggest the wire struct to have name `wire_...` to be consistent. Waiting for @Desdaemon 's opinion

**Comment by fzyzcjy** [comment]
Oops misclicked that button. Meant to click that for another PR

File: frb_example/pure_dart/dart/lib/main.dart (hunk 2 above)
Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:259]: Given @Desdaemon has not replied yet, I guess he may not have strong disagreement about this topic :)

Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:259]: You know what, I'll try to get the refactoring into `wire_...` done by Monday on a separate branch so you guys both have a chance to see if it's what you want or not :)

Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:259]: Take your time :) IMHO it is also completely ok to directly write it in this branch since that simplifies coding

Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:259]: I must admit I kinda lost the thread of which method generates what inside codegen, so I'm having a hard time finding where the changes should be made @fzyzcjy

Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:259]: furthermore, I think it's partly already the case, looking at the current state of the code, `wire_${enum_name}` is already generated :

```dart
// bridge_generated.dart
void _api_fill_to_wire_measure(Measure apiObj, wire_Measure wireObj) {
    if (apiObj is Measure_Speed_Variant) {
      wireObj.tag = 0;
      wireObj.kind = inner.inflate_Measure_Speed();
      wireObj.kind.ref.Speed.ref.field0 = _api2wire_box_speed(apiObj.field0);
    }
    if (apiObj is Measure_Distance_Variant) {
      wireObj.tag = 1;
      wireObj.kind = inner.inflate_Measure_Distance();
      wireObj.kind.ref.Distance.ref.field0 = _api2wire_box_distance(apiObj.field0);
    }
  }
```
where `wire_Measure` is:
```dart
// bridge_generated.dart
class wire_Measure extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external ffi.Pointer<MeasureKind> kind;
}
```
and `Measure` is:
```dart
// bridge_generated.dart
@freezed
class Measure with _$Measure {
  const factory Measure.speed(
    Speed field0,
  ) = Measure_Speed_Variant;
  const factory Measure.distance(
    Distance field0,
  ) = Measure_Distance_Variant;
}
```
So I'm reluctant to process this change as I think it's gonna require more cascading changes and increase the likeness of me introducing bugs/regressions.

Would you mind me leaving it the way it currently is ? @fzyzcjy

Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:259]: > lost the thread of which method generates what inside codegen, so I'm having a hard time finding where the changes should be made

Oops... What should I do? Shall I add a bit of doc or comments?

Btw I guess most generation are self-explanatory by looking at names.

This new chapter may be helpful: http://cjycode.com/flutter_rust_bridge/contributing/design.html

Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:259]: I see. So `Measure` seems like the struct that users are going to use, and `wire_Measure` is the one that we use internally on the "wire".

So, in the Measure example above, maybe we should simply rename Measure_Speed_Variant to Measure_Speed etc.  i.e. just simply remove "_Variant"

If this is hard, leaving the "_Variant" there looks also acceptable.

Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:259]: > So, in the Measure example above, maybe we should simply rename Measure_Speed_Variant to Measure_Speed etc. i.e. just simply remove "_Variant"
> 
> If this is hard, leaving the "_Variant" there looks also acceptable.

Yeah that bring us back to [this previous comment](https://github.com/fzyzcjy/flutter_rust_bridge/pull/604#discussion_r935045259) in the discussion.
If we strip `_Variant` suffix, then it also conflicts with pre-existing names.

Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:259]: Do we still have this problem? Looking at 

https://github.com/fzyzcjy/flutter_rust_bridge/blob/e63577dd126c03405bd207ec153aad222702cbce/frb_example/pure_dart/dart/lib/bridge_generated.dart
https://github.com/fzyzcjy/flutter_rust_bridge/blob/e63577dd126c03405bd207ec153aad222702cbce/frb_example/pure_dart/dart/lib/bridge_generated.freezed.dart

For "Measure" I see:

```
@freezed
class Measure with _$Measure {
  const factory Measure.speed(
    Speed field0,
  ) = Measure_Speed_Variant;
  const factory Measure.distance(
    Distance field0,
  ) = Measure_Distance_Variant;
}

...
abstract class Measure_Speed_Variant implements Measure {
and various others
```

but there is no Measure_Speed.

So I guess you can directly remove _Variant, and run codegen and everything (maybe previously we forget to run some codegen like freezed?)

If there is error please commit and push the code so I can see it. Currently that two files looks like no problem (if we remove variant suffix)

Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:259]: https://github.com/fzyzcjy/flutter_rust_bridge/blob/e63577dd12/frb_example/pure_dart/rust/src/bridge_generated.rs#L1234-L1257

I see. So it is clear now:

```rust
#[repr(C)]
#[derive(Clone)]
pub struct wire_Measure {
    tag: i32,
    kind: *mut MeasureKind,
}

#[repr(C)]
pub union MeasureKind {
    Speed: *mut Measure_Speed,
    Distance: *mut Measure_Distance,
}

#[repr(C)]
#[derive(Clone)]
pub struct Measure_Speed {
    field0: *mut wire_Speed,
}

#[repr(C)]
#[derive(Clone)]
pub struct Measure_Distance {
    field0: *mut wire_Distance,
}
```

We need to change the Measure_Speed into wire_Measure_Speed.
Notice that wire_Measure is correctly named (it has wire in it), but not Measure_Speed (should be wire_Measure_Speed)

(The discussion spanning too long time makes me forget everything from the memory... So sorry for confusion)

Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:259]: > (The discussion spanning too long time makes me forget everything from the memory... So sorry for confusion)

No worries, same here 😅 

Ok I tried adding the `wire_` prefix in the latest commit and pushed the codegen altogether @fzyzcjy

Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:259]: Seems almost finished now :)

```
error[E0412]: cannot find type `Distance_Unknown` in this scope
  --> src/bridge_generated.rs:46:19
   |
46 |     Unknown: *mut Distance_Unknown,
   |                   ^^^^^^^^^^^^^^^^ help: a struct with a similar name exists: `wire_Distance_Unknown`
...
52 | pub struct wire_Distance_Unknown {}
   | -------------------------------- similarly named struct `wire_Distance_Unknown` defined here
```

Just adding `wire_` to them and I guess we can merge it

Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:259]: done in these commits [6d51df0](https://github.com/fzyzcjy/flutter_rust_bridge/pull/604/commits/6d51df092b1f364f7e9f8950eb2e830794293ded) and [ebdfd81](https://github.com/fzyzcjy/flutter_rust_bridge/pull/604/commits/ebdfd81613b7f2dbcaf5b029a698bd372cd74908)

Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:259]: still outputting errors everywhere though 😓

Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:259]: almost 4k lines of code disappears... this may be the problem

image

Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:259]: Yes, any idea why?

Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:259]: oops your api.rs also lose a lot

image

Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:259]: Hmm so what's next ?

Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:259]: ensure api.rs is right :)

Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:259]: I don't mind digging further but tbh I won't have much time to allocate in the coming weeks so I'm worried it might go stale. If you want to take the lead and finish it I wouldn't mind!

Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:259]: Well, then maybe we should just leave it the original name and I will merge it.

Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart:259]: utterly agree! do you want me to force push to revert the latest commits?

Comment (fzyzcjy) [reply frb_example/pure_dart/dart/lib/main.dart:259]: It depends on you :) Git also has a feature called "revert" as well

Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart]: I might have found the missing bit, let's see CI outcome

Comment (Roms1383) [reply frb_example/pure_dart/dart/lib/main.dart]: @fzyzcjy looks like we can have the cake and eat it too 🍰 😄

**Review by fzyzcjy — APPROVED** [review]
Great job!
