### PR TITLE
Fix for #2899 "Windows 10 flutter_rust_bridge_codegen build-web fails (with solution)"

### LINKED ISSUE #2899: Windows 10 flutter_rust_bridge_codegen build-web fails
### Describe the bug

I'm developing in Windows 10.
Running a Flutter/Dart/Rust program in a browser such as chrome required these 3 commands:
```
PS> flutter_rust_bridge_codegen generate

PS> flutter_rust_bridge\target\debug\flutter_rust_bridge_codegen.exe build-web "--wasm-pack-rustflags=--cfg getrandom_backend=`\`"wasm_js`\`" -C target-feature=+atomics,+bulk-memory,+mutable-globals -C link-args=--shared-memory"

PS> flutter run -d chrome --wasm --web-header="Cross-Origin-Opener-Policy=same-origin" --web-header="Cross-Origin-Embedder-Policy=require-corp"
```
the second command converts the Rust code to wasm and fails for me with `Error: Fail to execute command, please see logs above for details.`:

```
PS> flutter_rust_bridge_codegen build-web "--wasm-pack-rustflags=--cfg getrandom_backend=`\`"wasm_js`\`" -C target-feature=+atomics,+bulk-memory,+mutable-globals -C link-args=--shared-memory"
[2025-09-28T14:49:48.387Z INFO frb_codegen\src\library\commands\fvm.rs:46] Installing Flutter version via FVM…
Building package executable...
Built flutter_rust_bridge:flutter_rust_bridge.
Unhandled exception:
Could not find an option or flag "-C".

Usage: flutter_rust_bridge build-web [arguments]
-h, --help                          Print this usage information.
    --dart-root                     Root folder of dart package
-c, --rust-root                     Directory of the rust package
                                    (defaults to "rust")
-o, --output=<PKG>                  Output path
    --release                       Compile in release mode
-v, --[no-]verbose                  Display more verbose information
    --cargo-build-args              Arguments passed to cargo-build
    --wasm-bindgen-args             Arguments passed to wasm-bindgen
    --wasm-pack-rustup-toolchain    Override RUSTUP_TOOLCHAIN environment variable when running wasm-pack
    --wasm-pack-rustflags           Override RUSTFLAGS environment variable when running wasm-pack
    --dart-compile-js-entrypoint    If specified, compile Dart into JavaScript and use this option as entrypoint

Run "flutter_rust_bridge help" to see global options.
#0      Command.usageException (package:args/command_runner.dart:466:7)
#1      CommandRunner.parse (package:args/command_runner.dart:140:15)
#2      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:36)
#3      new Future.sync (dart:async/future.dart:315:27)
#4      CommandRunner.run (package:args/command_runner.dart:122:14)
#5      main (file:///D:/NB__git_repos/github/flutter_rust_bridge/frb_dart/bin/flutter_rust_bridge.dart:14:16)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:312:33)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:12)
Error: Fail to execute command, please see logs above for details.
PS>
```

(as a work-around, I could instead run
```
PS> flutter_rust_bridge_codegen generate
PS> $Env:RUSTUP_TOOLCHAIN="nightly"
PS> $Env:RUSTFLAGS="--cfg getrandom_backend=`"wasm_js`" -C target-feature=+atomics,+bulk-memory,+mutable-globals -C link-args=--shared-memory"
PS> cd rust
PS> wasm-pack build -t no-modules -d D:\coding\gem_proj3\web/pkg --no-typescript --out-name rust_lib_gem_proj3 --dev . -- -Z build-std=std,panic_abort
PS> cd ..
PS> flutter run -d chrome --wasm --web-header="Cross-Origin-Opener-Policy=same-origin" --web-header="Cross-Origin-Embedder-Policy=require-corp"
```
but `flutter_rust_bridge_codegen build-web ...` command should run that command for the user and is simpler to use.)

I found a solution for the `flutter_rust_bridge_codegen build-web ...` error, but it involved modifying the flutter rust bridge code base in the file `flutter_rust_bridge\frb_codegen\src\library\commands\command_runner.rs`:
```
     ...
     pub(crate) fn call_shell_info(cmd: &[PathBuf]) -> CommandInfo {
 -       let cmd = cmd.iter().map(|section| format!("{section:?}")).join(" ");
     
         #[cfg(windows)]
 +       let cmd = cmd.iter().map(|section| windows_escape_for_powershell(&section.to_str().unwrap())).join(" ");
         return CommandInfo {
             program: "powershell".to_owned(),
             args: vec![
         };
     
         #[cfg(not(windows))]
 +       let cmd = cmd.iter().map(|section| format!("{section:?}")).join(" ");
         return CommandInfo {
             program: "sh".to_owned(),
             args: vec!["-c".to_owned(), cmd],
         };
     }
 +   
 +   pub fn windows_escape_for_powershell(section_in: &str) -> String {
 +       let mut section_out = String::new(); 
 +       for c in section_in.chars() {
 +           match c {
 +               '`' => section_out.push_str(r#"``"#), 
 +               '"' => section_out.push_str(r#"`""#), 
 +               '\\' => section_out.push_str(r#"`\"#), 
 +               ' ' => section_out.push_str(r#"` "#), 
 +               _ => section_out.push(c),       
 +           }
 +       }
 +       section_out 
 +   }
     
     #[derive(Default)]
     pub(crate) struct ExecuteCommandOptions {
         pub envs: Option<HashMap<String, String>>,
     ...
```     
The issue is that the `call_shell_info()` prepares the arguments for a `powershell` call but the line
```
let cmd = cmd.iter().map(|section| format!("{section:?}")).join(" ");
```
which wraps each argument in double-quotes not sufficient to escape arguments like 
```
--wasm-pack-rustflags=--cfg getrandom_backend=\"wasm_js\"
```
which needs the following powershell escapes
```
--wasm-pack-rustflags=--cfg` getrandom_backend=`\`"wasm_js`\`"
```
The only way I could get the correct powershell escapes was to run the arguments through the new `windows_escape_for_powershell()` function.
I would have created a pull request, but it seems that no one else is having this issue. Maybe they all use the above work-around, or maybe I am just not aware of a simpler solution. I realize that probably the best solution is to not develop in windows, but removing obstacles to windows users is better to get more of them to use and adopt the flutter rust bridge.

### Steps to reproduce

Documented above

### Logs

```shell
Note: it may look like the error 
  Could not find an option or flag "-C".
is occuring when
  "powershell" "-noprofile" "-command" "& \"fvm\" \"install\""
is executed, but this is not the case.

Output with env var RUSTLOG=debug:
PS>flutter_rust_bridge_codegen.exe build-web "--wasm-pack-rustflags=--cfg getrandom_backend=`\`"wasm_js`\`" -C target-feature=+atomics,+bulk-memory,+mutable-globals -C link-args=--shared-memory"
[2025-09-28T15:41:47.917Z DEBUG frb_codegen\src\main.rs:25] cli=Cli { verbose: false, command: BuildWeb(BuildWebCommandArgs { dart_root: None, dart_coverage: false, args: ["--wasm-pack-rustflags=--cfg getrandom_backend=\\\"wasm_js\\\" -C target-feature=+atomics,+bulk-memory,+mutable-globals -C link-args=--shared-memory"] }) }
[2025-09-28T15:41:47.918Z DEBUG frb_codegen\src\library\build_web\mod.rs:24] build dart_root="D:\\coding\\gem_proj3" args=["--wasm-pack-rustflags=--cfg getrandom_backend=\\\"wasm_js\\\" -C target-feature=+atomics,+bulk-memory,+mutable-globals -C link-args=--shared-memory"]
[2025-09-28T15:41:47.919Z DEBUG frb_codegen\src\library\utils\dart_repository\dart_repo.rs:25] Guessing toolchain the runner is run into
[2025-09-28T15:41:47.921Z DEBUG frb_codegen\src\library\utils\dart_repository\dart_repo.rs:326] Checking if "D:\\coding\\gem_proj3\\pubspec.yaml" is a workspace root pubspec...
[2025-09-28T15:41:47.921Z DEBUG frb_codegen\src\library\utils\dart_repository\dart_repo.rs:55] "D:\\coding\\gem_proj3" is not in a workspace
[2025-09-28T15:41:47.922Z DEBUG frb_codegen\src\library\commands\command_runner.rs:153] execute command: bin=powershell args="-noprofile -command & \"fvm\" \"--version\"" current_dir=None cmd="powershell" "-noprofile" "-command" "& \"fvm\" \"--version\""
[2025-09-28T15:41:48.303Z DEBUG frb_codegen\src\library\commands\command_runner.rs:164] command="powershell" "-noprofile" "-command" "& \"fvm\" \"--version\"" stdout=3.2.1
 stderr=
[2025-09-28T15:41:48.304Z INFO frb_codegen\src\library\commands\fvm.rs:46] Installing Flutter version via FVM…
[2025-09-28T15:41:48.304Z DEBUG frb_codegen\src\library\commands\command_runner.rs:153] execute command: bin=powershell args="-noprofile -command & \"fvm\" \"install\"" current_dir=None cmd="powershell" "-noprofile" "-command" "& \"fvm\" \"install\""
Building package executable...
Built flutter_rust_bridge:flutter_rust_bridge.
Unhandled exception:
Could not find an option or flag "-C".

Usage: flutter_rust_bridge build-web [arguments]
-h, --help                          Print this usage information.
    --dart-root                     Root folder of dart package
-c, --rust-root                     Directory of the rust package
                                    (defaults to "rust")
-o, --output=<PKG>                  Output path
    --release                       Compile in release mode
-v, --[no-]verbose                  Display more verbose information
    --cargo-build-args              Arguments passed to cargo-build
    --wasm-bindgen-args             Arguments passed to wasm-bindgen
    --wasm-pack-rustup-toolchain    Override RUSTUP_TOOLCHAIN environment variable when running wasm-pack
    --wasm-pack-rustflags           Override RUSTFLAGS environment variable when running wasm-pack
    --dart-compile-js-entrypoint    If specified, compile Dart into JavaScript and use this option as entrypoint

Run "flutter_rust_bridge help" to see global options.
#0      Command.usageException (package:args/command_runner.dart:466:7)
#1      CommandRunner.parse (package:args/command_runner.dart:140:15)
#2      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:36)
#3      new Future.sync (dart:async/future.dart:315:27)
#4      CommandRunner.run (package:args/command_runner.dart:122:14)
#5      main (file:///D:/NB__git_repos/github/flutter_rust_bridge/frb_dart/bin/flutter_rust_bridge.dart:14:16)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:312:33)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:12)
Error: Fail to execute command, please see logs above for details.
PS D:\coding\gem_proj3>
```

### Expected behavior

_No response_

### Generated binding code

```shell

```

### OS

Windows 10 Pro 22H2

### Version of `flutter_rust_bridge_codegen`

2.11.1

### Flutter info

```shell
PS> flutter doctor -v
[√] Flutter (Channel stable, 3.35.4, on Microsoft Windows [Version 10.0.19045.6396], locale en-CA) [597ms]
    • Flutter version 3.35.4 on channel stable at G:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d693b4b9db (12 days ago), 2025-09-16 14:27:41 +0000
    • Engine revision c298091351
    • Dart version 3.9.2
    • DevTools version 2.48.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios,
      cli-animations, enable-lldb-debugging

[√] Windows Version (10 Pro 64-bit, 22H2, 2009) [3.7s]

[√] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [4.4s]
    • Android SDK at C:\Users\marc\AppData\Local\Android\Sdk
    • Emulator version 35.6.11.0 (build_id 13610412) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • ANDROID_HOME = C:\Users\marc\AppData\Local\Android\Sdk
    • Java binary at: C:\tools\jdk-20.0.2\bin\java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 20.0.2+9-78)
    • All Android licenses accepted.

[√] Chrome - develop for the web [145ms]
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.14.12) [143ms]
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.14.36408.4
    • Windows 10 SDK version 10.0.26100.0

[√] Android Studio (version 2025.1.1) [14ms]
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)

[√] VS Code, 64-bit edition (version 1.104.2) [12ms]
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.118.0

[√] Connected device (3 available) [1,322ms]
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.6396]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 140.0.7339.208
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 140.0.3485.81

[√] Network resources [819ms]
    • All expected network resources are available.

• No issues found!
```

### Version of `clang++`

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marcmcd**
## Changes

Fixes #2899 "Windows 10 flutter_rust_bridge_codegen build-web fails (with solution)"

## Procedure and Checklist

In order to quickly iterate and avoid slowing down development pace by making CI pass, only the following simplified steps are needed, and I (fzyzcjy) will handle the rest of CI / moving the tests currently (will have more automation in the future).

- [ ✓ ] Implement the feature / fix the bug.
- [ ✓ ] Add tests in `frb_codegen/src/library/commands/command_runner.rs`.
- [ ✓? ] Add tests in `frb_example/dart_minimal` (tests added to `command_runner.rs` instead)
- [ ✓ ] Make `dart_minimal`'s CI green.

Utility commands
- Run codegen on Windows in PowerShell 7: `flutter_rust_bridge_codegen build-web "--wasm-pack-rustflags=--cfg getrandom_backend=`\`"wasm_js`\`" -C target-feature=+atomics,+bulk-memory,+mutable-globals -C link-args=--shared-memory"`
- Run tests: `cargo.exe test --package flutter_rust_bridge_codegen --lib -- library::commands::command_runner::tests --show-output `

### CODE REVIEW

File: frb_codegen/src/library/commands/command_runner.rs [hunk 1]
```diff
@@ -83,29 +83,81 @@ pub(crate) fn call_shell(
     command_run!(program in pwd, options = options, *args)
 }
 
+#[derive(Debug, PartialEq)]
```
Comment (marcmcd) [inline frb_codegen/src/library/commands/command_runner.rs:86]: `#[derive(Debug, PartialEq)]` attributes are required for test assertion `assert_eq!(actual, expect);`

Comment (fzyzcjy) [reply frb_codegen/src/library/commands/command_runner.rs:86]: no worries that looks reasonable

**Comment by fzyzcjy** [comment]
Great job! Feel free to ping me when it is ready

**Comment by marcmcd** [comment]
> Great job! Feel free to ping me when it is ready

PING! i'm no expert, but i think it's ready

**Comment by fzyzcjy** [comment]
Great job! one final check: does the latest code run well on your windows computer, i.e. does it solve the issue mentioned earlier? If so I will just merge :)

**Comment by marcmcd** [comment]
Yes, this fixes issue #2899 on my windows 10 computer.
I tested it many times in the PowerShell 7 CLI terminal.
I just tested it now in a CMD CLI terminal and it also works:
```
D:\coding\gem_proj3>D:\NB__git_repos\github\flutter_rust_bridge\target\debug\flutter_rust_bridge_codegen.exe build-web "--wasm-pack-rustflags=--cfg getrandom_backend=\\\"wasm_js\\\" -C target-feature=+atomics,+bulk-memory,+mutable-globals -C link-args=--shared-memory"
```
(I just had to replace the Powershell backtick escapes with backslash escapes, i.e.   `` `\`"wasm_js`\`" ``  --> ` \\\"wasm_js\\\" `)

**Comment by fzyzcjy** [comment]
@all-contributors please add marcmcd for code
