### PR TITLE
[fix] Add support for the optional hasher argument on HashMap and HashSet

### LINKED ISSUE #2565: Can't use std::collections::HashMap with custom hasher
### Describe the bug

Rust's `HashMap<K,V>` is translated to a `Map<K, V>` in Dart, but this doesn't work for non-default hashers.

### Steps to reproduce

```sh
flutter_rust_bridge_codegen create hashmap_example
cd hashmap_example/rust
cargo add fxhash
```

Replace `rust/src/api/simple.rs` with the following:

```rust
use std::collections::HashMap;

use fxhash::FxBuildHasher;

#[flutter_rust_bridge::frb(sync)]
pub fn greet(name: String) -> HashMap<String, String> {
    let mut map = HashMap::default();
    map.insert("message".to_owned(), format!("Hello, {name}!"));
    map
}

#[flutter_rust_bridge::frb(sync)]
pub fn greet2(name: String) -> HashMap<String, String, FxBuildHasher> {
    let mut map = HashMap::default();
    map.insert("message".to_owned(), format!("Hello, {name}!"));
    map
}

#[flutter_rust_bridge::frb(init)]
pub fn init_app() {
    flutter_rust_bridge::setup_default_user_utils();
}

```

run:

```sh
flutter_rust_bridge_codegen generate
```

### Expected behavior

For the Dart side, the hasher on the Rust side shouldn't matter.

However, the following code is generated:

```dart
// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Map<String, String> greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

HashMapStringStringFxBuildHasher greet2({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet2(name: name);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HashMap < String , String , FxBuildHasher >>>
abstract class HashMapStringStringFxBuildHasher
    implements RustOpaqueInterface {}
```

Note how `HashMapStringStringFxBuildHasher` is just an opaque class that can't be used from Dart.

### OS

Archlinux

### Version of `flutter_rust_bridge_codegen`

2.8.0

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.29.0, on Arch Linux 6.13.2-arch1-1, locale en_US.UTF-8) [50ms]
    • Flutter version 3.29.0 on channel stable at /home/anlumo/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 35c388afb5 (9 days ago), 2025-02-10 12:48:41 -0800
    • Engine revision f73bfc4522
    • Dart version 3.7.0
    • DevTools version 2.42.2

[✗] Android toolchain - develop for Android devices [26ms]
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web [14ms]
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop [114ms]
    • clang version 19.1.7
    • cmake version 3.31.5
    • ninja version 1.12.1
    • pkg-config version 2.3.0

[!] Android Studio (not installed) [13ms]
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] Connected device (3 available) [74ms]
    • Linux (desktop)                 • linux    • linux-x64      • Arch Linux 6.13.2-arch1-1
    • Chrome (web)                    • chrome   • web-javascript • Chromium 133.0.6943.98 Arch Linux
    • Catalyst Custom Launch (mobile) • catalyst • linux-x64      •

[✓] Network resources [508ms]
    • All expected network resources are available.

! Doctor found issues in 2 categories
```

### Version of `clang++`

19.1.7

### PR DESCRIPTION
**Pull request by anlumo**
## Changes

Fixes #2565

## Checklist

- [X] An issue to be fixed by this PR is listed above.
- [X] New tests are added to ensure new features are working.
- [X] `./frb_internal precommit --mode slow` (or `fast`) is run.
- [ ] ~~If this PR adds/changes features, documentations (in the `./website` folder) are updated.~~
- [ ] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI.

### CODE REVIEW

**Comment by anlumo** [comment]
I don't understand the CI error:

```
   Compiling fxhash v0.2.1
   Compiling frb_example_pure_dart_example_external_lib v0.1.0 (/home/runner/work/flutter_rust_bridge/flutter_rust_bridge/frb_example/pure_dart/rust/example_external_lib)
   Compiling frb_example_pure_dart v0.1.0 (/home/runner/work/flutter_rust_bridge/flutter_rust_bridge/frb_example/pure_dart/rust)
error[E0432]: unresolved import `fxhash::FxHashBuilder`
 --> src/api/map_and_set.rs:3:5
  |
3 | use fxhash::FxHashBuilder;
  |     ^^^^^^^^^^^^^^^^^^^^^ no `FxHashBuilder` in the root
```

It even says that it's including the fxhash crate, why can't the compiler find it?

**Comment by anlumo** [comment]
Don't have the time to look into those CI failures right now.

**Comment by fzyzcjy** [comment]
Great job!

No worries, you can add things in `frb_example/dart_minimal` for a quick test, and if that one passes, I can take over and handle the rest codegen issues.

**Comment by anlumo** [comment]
> Great job!
> 
> No worries, you can add things in `frb_example/dart_minimal` for a quick test, and if that one passes, I can take over and handle the rest codegen issues.

I've already added two tests (one for HashMap and one for HashSet) to pure\_dart.

The problem right now is the test [CI / Generate :: Internal (pull_request)](https://github.com/fzyzcjy/flutter_rust_bridge/actions/runs/13436758702/job/37540804698?pr=2567), and I don't even know what it wants from me. I suspect that the autoformatter failed because some formatting is wrong, but I don't see where.

**Comment by fzyzcjy** [comment]
Try `./frb_internal generate-internal-frb-example-pure-dart`, which should generate code in pure_dart_pde by using code in pure_dart

**Comment by anlumo** [comment]
> Try `./frb_internal generate-internal-frb-example-pure-dart`, which should generate code in pure_dart_pde by using code in pure_dart
> 
> Then maybe run `./frb_internal precommit-generate` again

That caused changes in hundreds of files. It also didn't actually fix the problem and all tests failed.

Maybe you can run it on your system and add a commit? I think there's some setting on your machine that makes things different. Dart autoformatting generated on my end always looks different than the one in the repository. I usually fix things manually to get around this.

**Comment by fzyzcjy** [comment]
Ok, sure!

File: frb_codegen/src/library/codegen/ir/mir/ty/delegate.rs [hunk 1]
```diff
@@ -169,9 +180,24 @@ impl MirTypeTrait for MirTypeDelegate {
...
+                if let Some(hasher) = &mir.hasher {
+                    format!(
+                        "Map_{}_{}_{}",
+                        mir.key.safe_ident(),
+                        mir.value.safe_ident(),
+                        hasher.safe_ident(),
+                    )
+                } else {
+                    format!("Map_{}_{}", mir.key.safe_ident(), mir.value.safe_ident())
+                }
```
Comment (fzyzcjy) [inline frb_codegen/src/library/codegen/ir/mir/ty/delegate.rs:192]: nit: we can unify it by doing something like

                    format!(
                        "Map_{}_{}_{}",
                        mir.key.safe_ident(),
                        mir.value.safe_ident(),
                        hasher.map(|h| h.safe_ident()).unwrap_or("None"),
                    )

etc

File: frb_codegen/src/library/codegen/ir/mir/ty/delegate.rs [hunk 2]
```diff
@@ -169,9 +180,24 @@ impl MirTypeTrait for MirTypeDelegate {
...
+            }
+            MirTypeDelegate::Set(mir) => {
+                if let Some(hasher) = &mir.hasher {
+                    format!("Set_{}_{}", mir.inner.safe_ident(), hasher.safe_ident())
+                } else {
+                    format!("Set_{}", mir.inner.safe_ident())
+                }
```
Comment (fzyzcjy) [inline frb_codegen/src/library/codegen/ir/mir/ty/delegate.rs:199]: (same as above)

File: frb_codegen/src/library/codegen/ir/mir/ty/delegate.rs [hunk 3]
```diff
@@ -239,13 +265,32 @@ impl MirTypeTrait for MirTypeDelegate {
...
-                format!("std::collections::HashSet<{}>", mir.inner.rust_api_type())
+                if let Some(hasher) = &mir.hasher {
+                    format!(
+                        "std::collections::HashSet<{}, {}>",
+                        mir.inner.rust_api_type(),
+                        hasher.rust_api_type(),
+                    )
+                } else {
+                    format!("std::collections::HashSet<{}>", mir.inner.rust_api_type())
+                }
```
Comment (fzyzcjy) [inline frb_codegen/src/library/codegen/ir/mir/ty/delegate.rs:293]: nit: what about 

                    format!(
                        "std::collections::HashMap<{}, {}{postfix}>",
                        mir.key.rust_api_type(),
                        mir.value.rust_api_type(),
                        postfix = hasher.map(|h| format!(", {}", h.rust_api_type())).unwrap_or_default(),
                    )

File: frb_codegen/src/library/codegen/parser/mir/parser/ty/concrete.rs [hunk 4]
```diff
@@ -77,11 +77,28 @@ impl TypeParserWithContext<'_, '_, '_> {
...
+                }))
+            },
+            ("HashMap", [key, value, hasher]) => {
+                let key  = self.parse_type(key)?;
+                let value  = self.parse_type(value)?;
+                let hasher  = self.parse_type(hasher)?;
+                Delegate(MirTypeDelegate::Map(MirTypeDelegateMap {
+                    key: Box::new(key.clone()),
+                    value: Box::new(value.clone()),
+                    hasher: Some(Box::new(hasher)),
```
Comment (fzyzcjy) [inline frb_codegen/src/library/codegen/parser/mir/parser/ty/concrete.rs:91]: nit: maybe we can extract a function, say, `fn parse_mir_hash_map(key, value, hasher: Optional<...>)`, and call it in this two branches

(same for hashset)

File: frb_example/pure_dart/rust/Cargo.toml [hunk 5]
```diff
@@ -24,6 +24,7 @@ serde_json = "1.0" # Only used for comparison test
 protobuf = "=2.28.0" # Only used for comparison test
 tokio = { version = "1.34.0", features = ["rt"] }
 
+
```
Comment (fzyzcjy) [inline frb_example/pure_dart/rust/Cargo.toml:27]: nit: maybe we can revert this empty line

**Review by fzyzcjy — COMMENTED** [review]
LGTM! Only some quick nits

**Comment by anlumo** [comment]
I'm running into some issues in my code when using the PR... In frb_generated.rs, there's the following implementation generated:

```rust
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<HashMap<String, LoroValue, LoroHasher>>>
    for HashMap<String, LoroValue, LoroHasher> {}
```

but this conflicts with the generic implementation in `into_into_dart.rs`:

```rust
impl<KT, KD, VT, VD, S> IntoIntoDart<HashMap<KD, VD>> for HashMap<KT, VT, S> {}
```

I'm kinda confused how this works for default-hash HashMaps. Is there some kind of filter somewhere that stops the generator from generating the custom impl for HashMap and HashSet that just happens to miss the implementation for non-default hashers?

**Comment by fzyzcjy** [comment]
Not very sure about the question but a quick guess: What about

```
//                                                                                               |---- this one
impl<KT, KD, VT, VD, S> IntoIntoDart<HashMap<KD, VD, S>> for HashMap<KT, VT, S> {}
```

**Comment by anlumo** [comment]
I'm only getting the conflicting implementation on one of my machines, I guess I just have to clean build on that one. The other computers require my branch to compile.

**Comment by anlumo** [comment]
I'm kinda out of ideas how to get the CI to be happy. I tried a lot of things, but at this point I'm just trying random things and check the outcome.

`./frb_internal precommit --mode slow` shows a lot of errors, maybe that's related, I don't know. Stuff like

```
ProcessException: Bad exit code (1). If you want to see extra information, set FRB_DART_RUN_COMMAND_STDERR=1
```

but I have no idea what is expected there.

**Comment by fzyzcjy** [comment]
No worries, as long as you can do the following then I will do the rest:

* Make demos (e.g. copy-paste all relavent tests from frb_example/pure_dart to here) in frb_example/dart_minimal
* Inside dart_minimal folder, run `cargo run --manifest-path /path-to/flutter_rust_bridge/frb_codegen/Cargo.toml -- generate`
* Run native tests `./frb_internal test-dart-native --package frb_example/dart_minimal`
* And would be great for web tests `test-dart-web` as well

**Comment by anlumo** [comment]
I'm sorry, I don't understand these instructions.

* Isn't the point of dart\_minimal to be a minimal working example? Why do you want me to add a super-specific use case of having a HashMap with a custom hash function to this?
* I can't find any `test-dart-web`. The closest I could locate is `dart_web_test_entrypoint.dart`, which is duplicated a bunch across the whole directory tree. However, that's just the entry point for wasm builds, not a file for tests. I can't find any web-specific tests at all, but maybe they're just lost in the pile of files.

**Comment by fzyzcjy** [comment]
Oh, I mean

1. Just temporarily do that (to ensure everything works); I will revert it (or merge it to frb_example/pure_dart), no worries!
2. I mean, besides `./frb_internal test-dart-native --package frb_example/dart_minimal`, also try `./frb_internal test-dart-web --package frb_example/dart_minimal`
