### PR TITLE
StreamSink recursive intodart_type

### LINKED ISSUE #1839: Crate compilation error when using mirrored third party Enum in StreamSink
### Describe the bug

Encountered a rust compilation error when I had both a function to return a third-party Enum to Dart land and a function that writes said Enum to a `StreamSink`.

<details>
<summary>cargo check errors</summary>

```shell
error[E0277]: the trait bound `allo_isolate::ffi::DartCObject: From<MyEnum>` is not satisfied
   --> src\frb_generated.rs:100:47
    |
100 | ...                   .stream_sink::<_, crate::api::simple::MyEnum>(),
    |                        -----------      ^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `From<MyEnum>` is not implemented for `allo_isolate::ffi::DartCObject`, which is required by `MyEnum: IntoDart`
    |                        |
    |                        required by a bound introduced by this call
    |
    = help: the following other types implement trait `From<T>`:
              <allo_isolate::ffi::DartCObject as From<DartOpaque>>
              <allo_isolate::ffi::DartCObject as From<RustOpaqueBase<T, A>>>
    = note: required for `MyEnum` to implement `Into<allo_isolate::ffi::DartCObject>`
    = note: required for `MyEnum` to implement `IntoDart`
note: required by a bound in `flutter_rust_bridge::rust2dart::context::TaskRust2DartContext::<Rust2DartCodec>::stream_sink`
   --> C:\Users\Mira\.cargo\registry\src\index.crates.io-6f17d22bba15001f\flutter_rust_bridge-2.0.0-dev.28\src\rust2dart\context.rs:33:12
    |
30  |     pub fn stream_sink<T, D>(&self) -> StreamSinkBase<T, Rust2DartCodec>
    |            ----------- required by a bound in this associated function
...
33  |         D: IntoDart,
    |            ^^^^^^^^ required by this bound in `TaskRust2DartContext::<Rust2DartCodec>::stream_sink`

error[E0277]: the trait bound `MyEnum: IntoIntoDart<MyEnum>` is not satisfied
   --> src\frb_generated.rs:100:44
    |
100 | ...                   .stream_sink::<_, crate::api::simple::MyEnum>(),
    |                        -----------   ^ the trait `IntoIntoDart<MyEnum>` is not implemented for `MyEnum`
    |                        |
    |                        required by a bound introduced by this call
    |
    = help: the trait `IntoIntoDart<mirror_MyEnum>` is implemented for `MyEnum`
    = help: for that trait implementation, expected `mirror_MyEnum`, found `MyEnum`
note: required by a bound in `flutter_rust_bridge::rust2dart::context::TaskRust2DartContext::<Rust2DartCodec>::stream_sink`
   --> C:\Users\Mira\.cargo\registry\src\index.crates.io-6f17d22bba15001f\flutter_rust_bridge-2.0.0-dev.28\src\rust2dart\context.rs:32:12
    |
30  |     pub fn stream_sink<T, D>(&self) -> StreamSinkBase<T, Rust2DartCodec>
    |            ----------- required by a bound in this associated function
31  |     where
32  |         T: IntoIntoDart<D>,
    |            ^^^^^^^^^^^^^^^ required by this bound in `TaskRust2DartContext::<Rust2DartCodec>::stream_sink`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `rust_lib_repro_frb` (lib) due to 2 previous errors
```
</details>

Also, while preparing this repro, I noticed that apparently the mirrored 3rd party type must also implement Clone due to a derive(Clone) in `frb_generated.rs`, is this intended?
```rs
#[derive(Clone)]
pub struct mirror_MyEnum(crate::api::simple::MyEnum);
```

### Steps to reproduce

1. `flutter_rust_bridge_codegen create repro_frb`
2. `cd repro_frb`
3. `cargo new --lib rust-3rdparty`
4. Modify and add Enum in `rust-3rdparty/src/lib.rs`
    ```rs
    #[derive(Clone)]
    pub enum MyEnum {
        Foo,
        Bar,
        Baz,
    }
    ```
5. Modify `rust/Cargo.toml` to have dependency on `rust-3rdparty`
    ```toml
    [dependencies]
    rust-3rdparty = { path = "../rust-3rdparty" }
    ```
6. Modify `rust/src/api/simple.rs`
    ```rs
    pub use rust_3rdparty::MyEnum;
    
    use crate::frb_generated::StreamSink;
    
    #[flutter_rust_bridge::frb(mirror(MyEnum))]
    pub enum _MyEnum {
        Foo,
        Bar,
        Baz,
    }
    
    pub fn get_enum() -> MyEnum {
        MyEnum::Foo
    }
    
    pub fn stream_enum(_sink: StreamSink<MyEnum>) {}
    ```
7. `flutter_rust_bridge_codegen generate`

### Logs

```shell
N/A
```

### Expected behavior

Rust bridge can compile

### Generated binding code

_No response_

### OS

Windows

### Version of `flutter_rust_bridge_codegen`

2.0.0-dev.28

### Flutter info

_No response_

### Version of `clang++`

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SilverMira**
## Changes

Fixes #1839

## Checklist

- [X] An issue to be fixed by this PR is listed above.
- [X] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [X] `./frb_internal precommit --mode slow` (or `fast`) is run (it internal runs code generator, does auto formatting, etc).
- [X] ~~If this PR adds/changes features, documentations (in the `./website` folder) are updated.~~
- [X] CI is passing. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to solve a failed CI. *looks like there are flaky tests with integrate command*

## Remark for PR creator

- `./frb_internal --help` shows utilities for development.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Feel free to ping me when ready (or facing any problems) :)

**Comment by SilverMira** [comment]
I couldn't get `./frb_internal precommit --mode slow` to actually work. Went for `./frb_internal generate-internal-frb-example-pure-dart && ./frb_internal generate-run-frb-codegen-command-generate --package frb_example/pure_dart` but turns out it wasn't quite enough.
Had to run `./frb_internal generate-run-frb-codegen-command-generate --package frb_example/pure_dart_pde` as well, hopefully everything should be fine now :)

**Comment by SilverMira** [comment]
Also, while writing this fix, I found that there are also other edge cases with `StreamSink<T>` that doesn't quite work either. Particularly, I noticed `StreamSink<HashSet<MirrorEnum>>` and `StreamSink<Map<X, MirrorEnum>>` isn't generating compilable code either, there are probably other combinations with container types that don't get resolved correctly. We should probably open another issue for tracking these.

Will probably take a look at them at a later date since I plan to aggressively use `StreamSink` in one of my projects :)

**Comment by fzyzcjy** [comment]
For that precommit thing, one way may be `./frb_internal precommit-generate` (looks like things are already done).

For the command integrate CI, just manually modify things in https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_codegen/assets/integration_template, because the "integrate" command indeed copy-and-paste things from there to the frb_examples (in order to let end users be fast).

> We should probably open another issue for tracking these.
Will probably take a look at them at a later date since I plan to aggressively use StreamSink in one of my projects :)

Sure, take your time and looking forward!

**Comment by fzyzcjy** [comment]
> is there something in the codegen already that can conditionally put #[derive()] on the wrapper types depending on whether certain types are being generated?

Interesting! IIRC there may not have been such things.
One way is, as you mentioned, when seeing HashSet, letting its child have these derives.
Another way is (possibly easier to implement), if detect the `#[derive()]` macros on the original struct, letting the generated struct have the derives.

**Comment by SilverMira** [comment]
> if detect the `#[derive()]` macros on the original struct, letting the generated struct have the derives.

I don't think that would work either, for all we know, users may do `impl Hash for OpaqueStruct` themselves somewhere in the crate, maybe due to what they wrap in the struct is not Hash therefore they can't derive it automatically.

Another idea I had was to have a blanket implementation for wrapper types, currently wrapper types are concrete types `Local_Auto_...` or `mirror_...`, I'm not sure whether there were any sort of technical reason behind this. But from the generated code, it looks to me we can actually have something like this.
```rs
pub struct frb_Wrapper<T>(T)

impl <T: Hash> Hash for frb_Wrapper<T> {
   // Delegate hashing to inner type
}

impl IntoIntoDart<frb_Wrapper<OpaqueStruct>> for OpaqueStruct {
  // Same implementation on concrete type as before
}

// And other generated impls...
```

**Comment by fzyzcjy** [comment]
> Another idea I had was to have a blanket implementation for wrapper types
> I'm not sure whether there were any sort of technical reason behind this.

Good idea! I am also not sure whether that will work (IIRC I made a ton of new structs instead of one generic struct because of some reasons, *but those reasons may disappear during later refactors*, so yes this may work!), thus it would be great to firstly make some lightweight attempts to see whether it breaks something or not.

**Comment by SilverMira** [comment]
Side note, I did manage to find some way to check whether there is HashSet<OpaqueStruct> before emitting the `pub struct Wrapper` by using `context.ir_pack.distinct_types()` and tag on the derives, but it does seem like having a generic wrapper type is the better way forward if we can do that.

**Comment by SilverMira** [comment]
@fzyzcjy, I think the CI with generate is picking up wrongly on pubspec.lock being changed and failing
image

**Comment by fzyzcjy** [comment]
Just run that command (`./frb_internal ...` shown in the title of your screenshot) locally without `set-exit-if-changed` and commit the local changes, and I guess the CI will be happy.

**Comment by SilverMira** [comment]
Looks like ci is happy now, currently the pr includes the switch over from `Local_Auto_Something` and `mirror_Something` to `frb_wrapper<Something>` for the blanket implementation approach for Eq and Hash. Tests are passing and we have lesser code generated since there are no longer any concrete wrapper types. It's ready for review and hope things are fine 🚀

File: frb_codegen/src/library/codegen/generator/wire/rust/spec_generator/misc/mod.rs [hunk 1]
```diff
@@ -114,20 +113,8 @@ use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt,
...
-                r###"
-                #[derive(Clone)]
-                pub struct {}({});
-                "###,
-                wrapper_struct_name,
-                ty.rust_api_type(),
-            )
-        })
+fn generate_wrapper_struct(_ty: &IrType, _context: WireRustGeneratorContext) -> Option<String> {
+    None
```
Comment (fzyzcjy) [inline frb_codegen/src/library/codegen/generator/wire/rust/spec_generator/misc/mod.rs:117]: nit: if it is none, iirc we may be able to remove this function since it has default implementation

File: frb_codegen/src/library/codegen/parser/type_parser/enum_or_struct.rs [hunk 2]
```diff
@@ -109,10 +109,11 @@ fn compute_name_and_wrapper_name(
     mirror: bool,
 ) -> (NamespacedName, Option<String>) {
     let name = ident.to_string();
+    let namespace = NamespacedName::new(namespace.clone(), name);
```
Comment (fzyzcjy) [inline frb_codegen/src/library/codegen/parser/type_parser/enum_or_struct.rs:112]: nit: this variable may be named `namespaced_name` (instead of `namespace` which means a namespace without a name)

**Review by fzyzcjy — APPROVED** [review]
Good work! Ready to merge and only some quick nits

File: frb_example/pure_dart/rust/src/api/mirror.rs [hunk 3]
```diff
@@ -24,6 +24,7 @@ pub struct _ApplicationSettingsTwinNormal {
 }
 
 #[frb(mirror(ApplicationMode))]
+#[derive(PartialEq, Eq, Hash)]
```
[the remark this answers is not in the document]
Comment (SilverMira) [reply frb_example/pure_dart/rust/src/api/mirror.rs:27]: You are right, I think this was just what I forgot to remove after some testing

File: frb_rust/src/for_generated/boilerplate.rs [hunk 4]
```diff
@@ -20,6 +21,50 @@ macro_rules! frb_generated_boilerplate {
     };
 }
 
+#[doc(hidden)]
+#[macro_export]
+macro_rules! frb_generated_wrapper_types {
+    () => {
+        #[doc(hidden)]
+        pub(crate) struct frb_wrapper<T>(T);
```
[the remark this answers is not in the document]
Comment (SilverMira) [reply frb_rust/src/for_generated/boilerplate.rs:29]: Yeah we can do that, the rationale I had when having it frb_wrapper was that it sort of mimicked the mirror_Something and also the type is probably something the user should never import/touch, but we can't hide it since it breaks streamsink

[the remark this answers is not in the document]
Comment (fzyzcjy) [reply frb_rust/src/for_generated/boilerplate.rs:29]: Anyway it is minor problem, since users should never touch it. I agree frb's internal (i.e. auto-generated and non-user-facing) naming is somehow a mixture of various styles...

**Comment by fzyzcjy** [comment]
(no worries about the flaky ios failure)

File: frb_example/pure_dart/test/api/pseudo_manual/mirror_twin_sync_sse_test.dart [hunk 5]
```diff
@@ -149,6 +149,67 @@ Future<void> main({bool skipRustLibInit = false}) async {
...
+        ApplicationMode.embedded,
+        ApplicationMode.standalone,
+      ])
+    ]);
+  });
+
+  test('mirror_array_enum_stream_twin_normal', () async {
+    final output = await mirrorArrayEnumStreamTwinSyncSse().toList();
+    expect(output, [
+      orderedEquals([
```
Comment (fzyzcjy) [inline frb_example/pure_dart/test/api/pseudo_manual/mirror_twin_sync_sse_test.dart:207]: nit: IIRC dart supports nested array comparison, e.g. `expect([[1,2]], [[1,2]])`. Is there any reasons to use orderedEquals?

**Review by fzyzcjy — APPROVED** [review]
LGTM! Just one tiny nit and you can choose not to modify it

File: frb_example/pure_dart/test/api/pseudo_manual/mirror_twin_sync_sse_test.dart (hunk 5 above)
Comment (SilverMira) [reply frb_example/pure_dart/test/api/pseudo_manual/mirror_twin_sync_sse_test.dart:207]: Tbh I just looked up for array matchers and the first thing I found was orderedEquals, so no real reason I suppose 😶

Comment (fzyzcjy) [reply frb_example/pure_dart/test/api/pseudo_manual/mirror_twin_sync_sse_test.dart:207]: I see, no problem! If you want to simplify it I will merge after that, otherwise I will merge now.

Comment (SilverMira) [reply frb_example/pure_dart/test/api/pseudo_manual/mirror_twin_sync_sse_test.dart:207]: If it's not gonna be a problem, then let's just go ahead 🚀
