### PR TITLE
Adjust type constraints to allow mirror types in Streams

### LINKED ISSUE #1275: [Bug] StreamSink<> of mirrored types creates wrong rust code
### Describe the bug

I have a function in my api.rs file that takes a StreamSink<LogEntry> where LogEntry comes from another rust crate.
For frb-codegen to work i have to add a frb(mirror..) struct for that LogEntry.
This makes the codegen work but creates an error in the rust code that prevents it from compiling.

It wraps the return of the funtcion in a mirror_LogEntry(), but the correct return value is (). LogEntry is just the StreamSink type.
Here is part of the generated code:
```rs
fn wire_init_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "init",
            port: Some(port_),
            mode: FfiCallMode::Stream,
        },
        move || move |task_callback| Ok(mirror_LogEntry(init(task_callback.stream_sink()))),
    )
}
```
If i remove the mirror_LogEntry() around the init call everything compiles and works fine.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
2023/07/12 12:32:17 [DEBUG] configs=[Opts { rust_input_path: "/home/manuel/programming/flutter_logger/example/dart/rust_lib/src/api.rs", dart_output_path: "/home/manuel/programming/flutter_logger/example/dart/bin/generated.dart", dart_decl_output_path: None, c_output_path: ["/tmp/.tmpDRkig2.h"], rust_crate_dir: "/home/manuel/programming/flutter_logger/example/dart/rust_lib", rust_output_path: "/home/manuel/programming/flutter_logger/example/dart/rust_lib/src/bridge_generated.rs", class_name: "RustLib", dart_format_line_length: 80, dart_enums_style: false, skip_add_mod_to_lib: false, llvm_path: ["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/msys64/mingw64"], llvm_compiler_opts: "", manifest_path: "/home/manuel/programming/flutter_logger/example/dart/rust_lib/Cargo.toml", dart_root: Some("/home/manuel/programming/flutter_logger/example/dart"), build_runner: true, block_index: BlockIndex(0), skip_deps_check: false, wasm_enabled: false, inline_rust: false, bridge_in_method: true, extra_headers: "", dart3: true }]
2023/07/12 12:32:17 [DEBUG] Trying to parse "/home/manuel/programming/flutter_logger/example/dart/rust_lib/src/api.rs"
2023/07/12 12:32:17 [DEBUG] Trying to parse "/home/manuel/programming/flutter_logger/example/dart/rust_lib/src/bridge_generated.rs"
2023/07/12 12:32:17 [WARN] Skipping unresolvable module io (tried /home/manuel/programming/flutter_logger/example/dart/rust_lib/src/io.rs, /home/manuel/programming/flutter_logger/example/dart/rust_lib/src/io/mod.rs, /home/manuel/programming/flutter_logger/example/dart/rust_lib/src/bridge_generated/io.rs, /home/manuel/programming/flutter_logger/example/dart/rust_lib/src/bridge_generated/io/mod.rs, )
2023/07/12 12:32:17 [DEBUG] parse_function function name: Ident(test)
2023/07/12 12:32:17 [DEBUG] parse_function function name: Ident(get_log_entry)
2023/07/12 12:32:17 [DEBUG] parse_function function name: Ident(init)
2023/07/12 12:32:17 [INFO] Phase: Validate config(s)
2023/07/12 12:32:17 [INFO] Picked config: Opts { rust_input_path: "/home/manuel/programming/flutter_logger/example/dart/rust_lib/src/api.rs", dart_output_path: "/home/manuel/programming/flutter_logger/example/dart/bin/generated.dart", dart_decl_output_path: None, c_output_path: ["/tmp/.tmpDRkig2.h"], rust_crate_dir: "/home/manuel/programming/flutter_logger/example/dart/rust_lib", rust_output_path: "/home/manuel/programming/flutter_logger/example/dart/rust_lib/src/bridge_generated.rs", class_name: "RustLib", dart_format_line_length: 80, dart_enums_style: false, skip_add_mod_to_lib: false, llvm_path: ["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/msys64/mingw64"], llvm_compiler_opts: "", manifest_path: "/home/manuel/programming/flutter_logger/example/dart/rust_lib/Cargo.toml", dart_root: Some("/home/manuel/programming/flutter_logger/example/dart"), build_runner: true, block_index: BlockIndex(0), skip_deps_check: false, wasm_enabled: false, inline_rust: false, bridge_in_method: true, extra_headers: "", dart3: true }
2023/07/12 12:32:17 [INFO] Phase: Parse source code to AST, then to IR
2023/07/12 12:32:17 [DEBUG] Trying to parse "/home/manuel/programming/flutter_logger/example/dart/rust_lib/src/api.rs"
2023/07/12 12:32:17 [DEBUG] Trying to parse "/home/manuel/programming/flutter_logger/example/dart/rust_lib/src/bridge_generated.rs"
2023/07/12 12:32:17 [WARN] Skipping unresolvable module io (tried /home/manuel/programming/flutter_logger/example/dart/rust_lib/src/io.rs, /home/manuel/programming/flutter_logger/example/dart/rust_lib/src/io/mod.rs, /home/manuel/programming/flutter_logger/example/dart/rust_lib/src/bridge_generated/io.rs, /home/manuel/programming/flutter_logger/example/dart/rust_lib/src/bridge_generated/io/mod.rs, )
2023/07/12 12:32:17 [DEBUG] parse_function function name: Ident(test)
2023/07/12 12:32:17 [DEBUG] parse_function function name: Ident(get_log_entry)
2023/07/12 12:32:17 [DEBUG] parse_function function name: Ident(init)
2023/07/12 12:32:17 [INFO] Phase: Transform IR
2023/07/12 12:32:17 [INFO] Phase: Generate Rust code
2023/07/12 12:32:17 [DEBUG] execute format_rust path=["/home/manuel/programming/flutter_logger/example/dart/rust_lib/src/bridge_generated.rs"]
2023/07/12 12:32:17 [DEBUG] execute command: bin=rustfmt args="/home/manuel/programming/flutter_logger/example/dart/rust_lib/src/bridge_generated.rs" current_dir=None cmd="rustfmt" "/home/manuel/programming/flutter_logger/example/dart/rust_lib/src/bridge_generated.rs"
2023/07/12 12:32:17 [DEBUG] command="rustfmt" "/home/manuel/programming/flutter_logger/example/dart/rust_lib/src/bridge_generated.rs" stdout= stderr=
2023/07/12 12:32:17 [INFO] Phase: Generate Dart code
2023/07/12 12:32:17 [DEBUG] Guessing toolchain the runner is run into
2023/07/12 12:32:17 [DEBUG] execute command: bin=sh args="-c \"dart\" \"--version\"" current_dir=None cmd="sh" "-c" "\"dart\" \"--version\""
Dart SDK version: 3.0.5 (stable) (Mon Jun 12 18:31:49 2023 +0000) on "linux_x64"
2023/07/12 12:32:17 [DEBUG] command="sh" "-c" "\"dart\" \"--version\"" stdout= stderr=
2023/07/12 12:32:17 [DEBUG] Checking presence of ffi in dependencies at /home/manuel/programming/flutter_logger/example/dart
2023/07/12 12:32:17 [DEBUG] Checking presence of ffi in dependencies at /home/manuel/programming/flutter_logger/example/dart
2023/07/12 12:32:17 [DEBUG] Checking presence of ffigen in dev_dependencies at /home/manuel/programming/flutter_logger/example/dart
2023/07/12 12:32:17 [DEBUG] Checking presence of ffigen in dev_dependencies at /home/manuel/programming/flutter_logger/example/dart
2023/07/12 12:32:17 [INFO] Phase: Generating Dart bindings for Rust
2023/07/12 12:32:17 [DEBUG] execute cbindgen rust_crate_dir=/home/manuel/programming/flutter_logger/example/dart/rust_lib c_output_path=/tmp/.tmpvPbbaf.h
2023/07/12 12:32:17 [DEBUG] cbindgen config: Config {
    header: None,
    includes: [],
    sys_includes: [
        "stdbool.h",
        "stdint.h",
        "stdlib.h",
    ],
    after_includes: Some(
        "typedef struct _Dart_Handle* Dart_Handle;",
    ),
    trailer: None,
    include_guard: None,
    pragma_once: false,
    no_includes: true,
    autogen_warning: None,
    include_version: false,
    namespace: None,
    namespaces: None,
    using_namespaces: None,
    braces: SameLine,
    line_length: 100,
    tab_width: 2,
    line_endings: LF,
    language: C,
    cpp_compat: false,
    style: Both,
    sort_by: None,
    usize_is_size_t: false,
    parse: ParseConfig {
        parse_deps: false,
        include: None,
        exclude: [],
        expand: ParseExpandConfig {
            crates: [],
            all_features: false,
            default_features: true,
            features: None,
            profile: Debug,
        },
        clean: false,
        extra_bindings: [],
    },
    export: ExportConfig {
        include: [
            "\"wire_LogEntry\"",
        ],
        exclude: [],
        rename: {},
        pre_body: {},
        body: {},
        prefix: None,
        item_types: [],
        renaming_overrides_prefixing: false,
        mangle: MangleConfig {
            rename_types: None,
            remove_underscores: false,
        },
    },
    macro_expansion: MacroExpansionConfig {
        bitflags: false,
    },
    layout: LayoutConfig {
        packed: None,
        aligned_n: None,
    },
    function: FunctionConfig {
        prefix: None,
        postfix: None,
        must_use: None,
        args: Auto,
        rename_args: None,
        swift_name_macro: None,
        sort_by: None,
        no_return: None,
    },
    structure: StructConfig {
        rename_fields: None,
        derive_constructor: false,
        derive_eq: false,
        derive_neq: false,
        derive_lt: false,
        derive_lte: false,
        derive_gt: false,
        derive_gte: false,
        derive_ostream: false,
        associated_constants_in_body: false,
        must_use: None,
    },
    enumeration: EnumConfig {
        rename_variants: None,
        rename_variant_name_fields: SnakeCase,
        add_sentinel: false,
        prefix_with_name: false,
        derive_helper_methods: false,
        derive_const_casts: false,
        derive_mut_casts: false,
        cast_assert_name: None,
        must_use: None,
        derive_tagged_enum_destructor: false,
        derive_tagged_enum_copy_constructor: false,
        derive_tagged_enum_copy_assignment: false,
        derive_ostream: false,
        enum_class: true,
        private_default_tagged_enum_constructor: false,
    },
    constant: ConstantConfig {
        allow_static_const: true,
        allow_constexpr: true,
        sort_by: None,
    },
    defines: {},
    documentation: true,
    documentation_style: Auto,
    documentation_length: Full,
    pointer: PtrConfig {
        non_null_attribute: None,
    },
    only_target_dependencies: false,
    cython: CythonConfig {
        header: None,
        cimports: {},
    },
}
2023/07/12 12:32:18 [DEBUG] Parsing crate rust_lib
2023/07/12 12:32:18 [INFO] Take rust_lib::_LogEntry - opaque (Struct is not marked #[repr(C)] or #[repr(transparent)].).
2023/07/12 12:32:18 [INFO] Take rust_lib::_LogLevel - opaque (Enum is not marked with a valid #[repr(prim)] or #[repr(C)].).
2023/07/12 12:32:18 [INFO] Take rust_lib::mirror_LogEntry - opaque (Struct is not marked #[repr(C)] or #[repr(transparent)].).
2023/07/12 12:32:18 [INFO] Take rust_lib::mirror_LogLevel - opaque (Struct is not marked #[repr(C)] or #[repr(transparent)].).
2023/07/12 12:32:18 [WARN] Skip rust_lib::_ - (not `pub`).
2023/07/12 12:32:18 [INFO] Take rust_lib::DartPort.
2023/07/12 12:32:18 [INFO] Take rust_lib::DartPostCObjectFnType.
2023/07/12 12:32:18 [INFO] Take rust_lib::store_dart_post_cobject.
2023/07/12 12:32:18 [INFO] Take rust_lib::get_dart_object.
2023/07/12 12:32:18 [INFO] Take rust_lib::drop_dart_object.
2023/07/12 12:32:18 [INFO] Take rust_lib::new_dart_opaque.
2023/07/12 12:32:18 [INFO] Take rust_lib::init_frb_dart_api_dl.
2023/07/12 12:32:18 [INFO] Take rust_lib::DartCObject - opaque (Struct is not marked #[repr(C)] or #[repr(transparent)].).
2023/07/12 12:32:18 [INFO] Take rust_lib::WireSyncReturn.
2023/07/12 12:32:18 [INFO] Take rust_lib::wire_test.
2023/07/12 12:32:18 [INFO] Take rust_lib::wire_get_log_entry.
2023/07/12 12:32:18 [INFO] Take rust_lib::wire_init.
2023/07/12 12:32:18 [INFO] Take rust_lib::free_WireSyncReturn.
2023/07/12 12:32:18 [WARN] Can't find Dart_Handle. This usually means that this type was incompatible or not found.
2023/07/12 12:32:18 [WARN] Can't find Dart_Handle. This usually means that this type was incompatible or not found.
2023/07/12 12:32:18 [WARN] Missing `[defines]` entry for `target_family = "wasm"` in cbindgen config.
2023/07/12 12:32:18 [WARN] Missing `[defines]` entry for `target_family = "wasm"` in cbindgen config.
2023/07/12 12:32:18 [WARN] Missing `[defines]` entry for `target_family = "wasm"` in cbindgen config.
2023/07/12 12:32:18 [WARN] Missing `[defines]` entry for `target_family = "wasm"` in cbindgen config.
2023/07/12 12:32:18 [DEBUG] execute ffigen c_path=/tmp/.tmpvPbbaf.h dart_path=/tmp/.tmpzDj3rj llvm_path=["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/msys64/mingw64"]
2023/07/12 12:32:18 [DEBUG] ffigen config: 
        output: '/tmp/.tmpzDj3rj'
        name: 'RustLibWire'
        description: 'generated by flutter_rust_bridge'
        headers:
          entry-points:
            - '/tmp/.tmpvPbbaf.h'
          include-directives:
            - '/tmp/.tmpvPbbaf.h'
        comments: false
        preamble: |
          // ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
        
        llvm-path:
           - '/opt/homebrew/opt/llvm'
           - '/usr/local/opt/llvm'
           - '/usr/lib/llvm-9'
           - '/usr/lib/llvm-10'
           - '/usr/lib/llvm-11'
           - '/usr/lib/llvm-12'
           - '/usr/lib/llvm-13'
           - '/usr/lib/llvm-14'
           - '/usr/lib/'
           - '/usr/lib64/'
           - 'C:/Program Files/llvm'
           - 'C:/msys64/mingw64'

2023/07/12 12:32:18 [DEBUG] ffigen config_file: NamedTempFile("/tmp/.tmpO2r3dA")
2023/07/12 12:32:18 [DEBUG] Guessing toolchain the runner is run into
2023/07/12 12:32:18 [DEBUG] execute command: bin=sh args="-c \"dart\" \"run\" \"ffigen\" \"--config\" \"/tmp/.tmpO2r3dA\"" current_dir=Some("/home/manuel/programming/flutter_logger/example/dart") cmd=cd "/home/manuel/programming/flutter_logger/example/dart" && "sh" "-c" "\"dart\" \"run\" \"ffigen\" \"--config\" \"/tmp/.tmpO2r3dA\""
Running in Directory: '/home/manuel/programming/flutter_logger/example/dart'
Input Headers: [/tmp/.tmpvPbbaf.h]
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: DartCObject, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct DartCObject, usr: c:@S@DartCObject
[WARNING]: No definition found for declaration - (Cursor) spelling: DartCObject, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct DartCObject, usr: c:@S@DartCObject
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: DartCObject, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct DartCObject, usr: c:@S@DartCObject
[WARNING]: Generated declaration '_Dart_Handle' start's with '_' and therefore will be private.
Finished, Bindings generated in /tmp/.tmpzDj3rj
2023/07/12 12:32:18 [DEBUG] command=cd "/home/manuel/programming/flutter_logger/example/dart" && "sh" "-c" "\"dart\" \"run\" \"ffigen\" \"--config\" \"/tmp/.tmpO2r3dA\"" stdout= stderr=
the path is "/tmp/.tmpDRkig2.h"
2023/07/12 12:32:18 [DEBUG] distinct_input_types=[Primitive(I32)]
2023/07/12 12:32:18 [DEBUG] distinct_output_types=[Delegate(String), Primitive(I32), Primitive(I64), StructRef(IrTypeStructRef { name: "LogEntry", freezed: false, empty: false }), Delegate(PrimitiveEnum { ir: IrTypeEnumRef { name: "LogLevel" }, repr: I32 }), Primitive(U8), PrimitiveList(IrTypePrimitiveList { primitive: U8 }), Primitive(Unit)]
2023/07/12 12:32:18 [INFO] Phase: Running build_runner
2023/07/12 12:32:18 [INFO] Phase: Formatting Dart code
2023/07/12 12:32:18 [DEBUG] execute format_dart path=["/home/manuel/programming/flutter_logger/example/dart/bin/generated.dart"] line_length=80
2023/07/12 12:32:18 [DEBUG] execute command: bin=sh args="-c \"dart\" \"format\" \"--line-length\" \"80\" \"/home/manuel/programming/flutter_logger/example/dart/bin/generated.dart\"" current_dir=None cmd="sh" "-c" "\"dart\" \"format\" \"--line-length\" \"80\" \"/home/manuel/programming/flutter_logger/example/dart/bin/generated.dart\""
Formatted /home/manuel/programming/flutter_logger/example/dart/bin/generated.dart
Formatted 1 file (1 changed) in 0.13 seconds.
2023/07/12 12:32:18 [DEBUG] command="sh" "-c" "\"dart\" \"format\" \"--line-length\" \"80\" \"/home/manuel/programming/flutter_logger/example/dart/bin/generated.dart\"" stdout= stderr=
2023/07/12 12:32:18 [INFO] Success!
2023/07/12 12:32:18 [INFO] Now go and use it :)
```

### To Reproduce

Create a funtion that takes a StreamSink<> of a mirrored type. Generate the code and try to compile the rust side.

### Expected behavior

generated code should compile without errors. Return value of the function (unit type) should not be wrapped in the mirror() struct

### Generated binding code

_No response_

### OS

linux

### Version of `flutter_rust_bridge_codegen`

1.78.0

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.10.5, on Manjaro Linux 6.1.38-1-MANJARO, locale en_US.UTF-8)
    • Flutter version 3.10.5 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /usr/lib/jvm/java-17-openjdk/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+7)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Manjaro Linux 6.1.38-1-MANJARO

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

### Version of `clang++`

15.0.7

### Version of `ffigen`

8.0.2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MnlPhlp**
## Changes

The basic idea is to crate a trait IntoIntoDart that can be used to convert a type to another type that then implements IntoDart. This can then be used as constraint for StreamSink to allow a type that converts to a mirror_type that then implements IntoDart.

I have some local changes that I didn't commit  yet. With some more generic impls and adjustments in the generator this removes explicit wrapping into mirror types basically everywhere, also in the generated code.

Fixes #1275 

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [x] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- [x] The code generator is run and the code is formatted (via `just precommit`).
- [x] If this PR adds/changes features, documentations (in the `./book` folder) are updated.
- [x] CI is passing.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Good job! Then I will wait until I can see the overall picture. Or feel free to provide some quick preview before implementing the whole thing for a quick review of ideas!

**Comment by MnlPhlp** [comment]
It works :D

For mirrored Types a Trait is generated that implements the add method on the matching StreamSink. For all Types that implement IntoDart themselves the StreamSinkTrait from the lib generates that method, so no code has to be generated for those types

Using the IntoIntoDart Trait also allowed removing the mirror_ wrapping in some other places

**Comment by fzyzcjy** [comment]
Great!

> For all Types that implement IntoDart themselves the StreamSinkTrait from the lib generates that method, so no code has to be generated for those types

I like that :) We should not generate unnecessary things

> Using the IntoIntoDart Trait also allowed removing the mirror_ wrapping in some other places

Also looks like good news!

I will review probably within 24 hours since really busy recently.

**Comment by MnlPhlp** [comment]
I just noticed i can get rid of the generated StreamSink traits completely. So there are no user visible changes add all.
I will commit that in a few minutes

**Comment by MnlPhlp** [comment]
Turns out we don't need any traits for the stream sink and can implement add directly with correct type constraints.

This prevents the change from breaking any code that just imports StreamSink instead of flutter_rust_bridge::*.

Now there should be no changes at all outside of generated code.

File: frb_rust/src/rust2dart.rs [hunk 1]
```diff
@@ -139,3 +145,120 @@ impl<T: IntoDart> StreamSink<T> {
         self.rust2dart().close_stream()
     }
 }
+
+/// Basically the Into trait.
+/// We need this separate trait because we need to implement int for Vec<T> etc.
```
Comment (fzyzcjy) [inline frb_rust/src/rust2dart.rs:150]: nit: typo?

```suggestion
/// We need this separate trait because we need to implement into for Vec<T> etc.
```

Comment (fzyzcjy) [inline frb_rust/src/rust2dart.rs:150]: nit: would be great to explain a bit more why, or at least point to this PR

File: frb_rust/src/rust2dart.rs [hunk 2]
```diff
@@ -139,3 +145,120 @@ impl<T: IntoDart> StreamSink<T> {
...
+pub trait IntoIntoDart<D> {
+    fn into_into_dart(self) -> D;
+}
+
+impl<T, D> IntoIntoDart<Vec<D>> for Vec<T>
+where
+    T: IntoIntoDart<D>,
+{
+    fn into_into_dart(mut self) -> Vec<D> {
+        self.drain(0..).map(|e| e.into_into_dart()).collect()
```
Comment (fzyzcjy) [inline frb_rust/src/rust2dart.rs:160]: nit: does this work?

```suggestion
        self.into_iter().map(|e| e.into_into_dart()).collect()
```

File: frb_rust/src/rust2dart.rs [hunk 3]
```diff
@@ -139,3 +145,120 @@ impl<T: IntoDart> StreamSink<T> {
...
+    }
+}
+
+impl<A, AD, B, BD> IntoIntoDart<(AD, BD)> for (A, B)
```
Comment (fzyzcjy) [inline frb_rust/src/rust2dart.rs:164]: nit: given that we need to give a ton of implementations to IntoIntoDart, what about extract it to a separate file, say into_into_dart.rs

File: frb_rust/src/rust2dart.rs [hunk 4]
```diff
@@ -129,8 +135,8 @@ impl<T: IntoDart> StreamSink<T> {
 
     /// Add data to the stream. Returns false when data could not be sent,
     /// or the stream has been closed.
-    pub fn add(&self, value: T) -> bool {
-        self.rust2dart().success(value)
+    pub fn add<V: IntoIntoDart<D> + TypeEquals<Other = T>, D: IntoDart>(&self, value: V) -> bool {
```
Comment (fzyzcjy) [inline frb_rust/src/rust2dart.rs:138]: nit: just a naive idea - does this work?

```suggestion
    pub fn add<D: IntoDart>(&self, value: T) -> bool where T: IntoIntoDart<D> {
```

File: frb_rust/src/rust2dart.rs [hunk 5]
```diff
@@ -74,7 +76,11 @@ impl TaskCallback {
     }
 
     /// Create a new [StreamSink] of the specified type.
-    pub fn stream_sink<T: IntoDart>(&self) -> StreamSink<T> {
+    pub fn stream_sink<T, D>(&self) -> StreamSink<T>
+    where
+        T: IntoIntoDart<D>,
+        D: IntoDart,
+    {
         StreamSink::new(self.rust2dart.clone())
```
Comment (fzyzcjy) [inline frb_rust/src/rust2dart.rs:84]: nit: is `D` used here or not? If not maybe we can remove it, then it is even easier for the generated code

File: frb_rust/src/rust2dart.rs [hunk 6]
```diff
@@ -139,3 +145,120 @@ impl<T: IntoDart> StreamSink<T> {
...
+    ($t:ty) => {
+        impl IntoIntoDart<$t> for $t {
+            fn into_into_dart(self) -> $t {
+                self
+            }
+        }
+    };
+}
+
+impl_into_into_dart!(u8);
```
Comment (fzyzcjy) [inline frb_rust/src/rust2dart.rs:233]: nit: btw did you copy it from somewhere? if so it is great to briefly point to there so it is easier to keep code in sync

**Review by fzyzcjy — COMMENTED** [review]
Partially checked the code (mainly the idea, but also go through details). Great job!

File: frb_rust/src/rust2dart.rs (hunk 1 above)
Comment (MnlPhlp) [reply frb_rust/src/rust2dart.rs:150]: i will expand the comment and link the pr

File: frb_rust/src/rust2dart.rs (hunk 2 above)
Comment (MnlPhlp) [reply frb_rust/src/rust2dart.rs:160]: yes it does. I will change that

File: frb_rust/src/rust2dart.rs (hunk 3 above)
Comment (MnlPhlp) [reply frb_rust/src/rust2dart.rs:164]: Sounds good. I can also add tuple impls up to 5 or so in that file.
I maybe also missed some types if there are some that are not in the test but worked before.

File: frb_rust/src/rust2dart.rs (hunk 4 above)
Comment (MnlPhlp) [reply frb_rust/src/rust2dart.rs:138]: Good idea. Yes that worked, then we can get rid of the TypeEquals dependency

File: frb_rust/src/rust2dart.rs (hunk 5 above)
Comment (MnlPhlp) [reply frb_rust/src/rust2dart.rs:84]: The `D` is needed as generic argument for the `IntoIntoDart` trait on `T`.
We could remove it if we allow any `T`. That is probably fine because `StreamSink` also allows every `T`. I just wanted to constrain it to detect errors in the generated code easier

File: frb_rust/src/rust2dart.rs (hunk 6 above)
Comment (MnlPhlp) [reply frb_rust/src/rust2dart.rs:233]: not really copied but i looked at the impls for `IntoDart`. I will add a comment for that

File: frb_rust/src/rust2dart.rs (hunk 5 above)
Comment (fzyzcjy) [reply frb_rust/src/rust2dart.rs:83]: I see, looks reasonable! Then it may be helpful to briefly add a comment why we do this

**Comment by MnlPhlp** [comment]
I just added a commit that addresses your comments

**Comment by fzyzcjy** [comment]
Feel free to `Resolve conversation` that you have done!

File: book/src/feature/logging.md
Comment (fzyzcjy) [inline book/src/feature/logging.md:1]: nit: maybe we can revert this change, since it only changes format

File: book/src/feature/stream.md
Comment (fzyzcjy) [inline book/src/feature/stream.md:1]: same

File: frb_rust/src/into_into_dart.rs [hunk 7]
```diff
@@ -0,0 +1,172 @@
+use crate::{ffi::*, DartSafe};
+
+/// Basically the Into trait.
+/// We need this separate trait because we need to implement it for Vec<T> etc.
+/// These blanket implementations allow us to accept external types in various places.
+/// The initial reason for this was to allow mirrored types in StreamSink<>.
+/// See also [PR 1285](https://github.com/fzyzcjy/flutter_rust_bridge/pull/1285)
+pub trait IntoIntoDart<D> {
```
Comment (fzyzcjy) [inline frb_rust/src/into_into_dart.rs:8]: nit: should we constrain that `D: IntoDart`? because the name `IntoIntoDart` does imply this

File: frb_codegen/src/generator/rust/mod.rs [hunk 8]
```diff
@@ -358,15 +359,20 @@ impl<'a> Generator<'a> {
...
-                "wrap",
+            IrFuncMode::Normal => (
+                format!("wrap::<_,_,_,{}>", func.output.intodart_type(ir_file)),
+                None,
+                format!("{code_wire2api} move |task_callback| {code_call_inner_func_result}"),
+            ),
+            IrFuncMode::Stream { .. } => (
+                String::from("wrap::<_,_,_,()>"),
                 None,
                 format!("{code_wire2api} move |task_callback| {code_call_inner_func_result}"),
```
Comment (fzyzcjy) [inline frb_codegen/src/generator/rust/mod.rs:377]: nit: looks like the two branches has a bit of code duplication which may be removeable

**Review by fzyzcjy — APPROVED** [review]
LGTM, only nits and I am ready to merge!

File: book/src/feature/logging.md
Comment (MnlPhlp) [reply book/src/feature/logging.md:1]: Yes, that was just my format on save setting when i undid the changes.

File: frb_rust/src/into_into_dart.rs (hunk 7 above)
Comment (MnlPhlp) [reply frb_rust/src/into_into_dart.rs]: Good idea, I added that.

File: frb_codegen/src/generator/rust/mod.rs (hunk 8 above)
Comment (MnlPhlp) [reply frb_codegen/src/generator/rust/mod.rs]: good point. I changed that

File: book/src/feature/logging.md [hunk 9]
```diff
@@ -162,4 +162,4 @@ class _MyHomePageState extends State<MyHomePage> {
     );
   }
 }
-```
\ No newline at end of file
+```
```
Comment (MnlPhlp) [inline book/src/feature/logging.md:165]: I don't know what changed here :D

File: book/src/feature/stream.md [hunk 10]
```diff
@@ -6,7 +6,7 @@ Flutter's [Stream](https://dart.dev/tutorials/language/streams) is a powerful ab
 
 For example, your Rust function may run computationally heavy algorithms, and for every hundreds of milliseconds, it finds out a new piece of the full solution. In this case, it can immediately give that piece to Flutter, then Flutter can render it to UI immediately. Therefore, users do not need to wait for the full algorithm to finish before he can see some partial results on the user interface.
 
-As for the details, a Rust function with signature like `fn f(sink: StreamSink<T>, ..) -> Result<()>` is translated to a Dart function  `Stream<T> f(..)`.
```
Comment (MnlPhlp) [inline book/src/feature/stream.md:9]: I don't think we should keep the extra space.

**Comment by MnlPhlp** [comment]
Should be done.

**Comment by fzyzcjy** [comment]
Great! I will briefly check soon

**Comment by MnlPhlp** [comment]
Added a test for a tuple. Turns out there was some code missing for tuples.
I checked all the types with some inner values, should be good now

File: book/src/feature/logging.md (hunk 9 above)
Comment (fzyzcjy) [reply book/src/feature/logging.md:165]: I also dnk... maybe just revert it

File: frb_example/pure_dart/rust/src/api.rs [hunk 11]
```diff
@@ -689,6 +689,39 @@ pub fn is_app_embedded(app_settings: ApplicationSettings) -> bool {
     matches!(app_settings.mode, ApplicationMode::Embedded)
 }
 
+// use a stream of a mirrored type
+pub fn app_settings_stream(sink: StreamSink<ApplicationSettings>) {
```
Comment (fzyzcjy) [inline frb_example/pure_dart/rust/src/api.rs:693]: nit: oops I forgot to mention this: please add a corresponding test in .dart, as the checklist of the PR says:

> New tests are added to ensure new features are working. End-to-end tests are usually in the ./frb_example/pure_dart example, more specifically, rust/src/api.rs and dart/lib/main.dart.

**Review by fzyzcjy — COMMENTED** [review]
Ready to merge after this nit + the nit above + CI pass (except for the long-lived macos problem)!

**Comment by fzyzcjy** [comment]
@all-contributors please add @MnlPhlp for code, doc

File: book/src/feature/logging.md (hunk 9 above)
Comment (MnlPhlp) [reply book/src/feature/logging.md:165]: the change is that there was no newline at the end of the file. Might be worth it to keep the change.

**Comment by MnlPhlp** [comment]
Should i also increase the version number or will that be done after the merge?
I added tests and everything seems to work

**Comment by fzyzcjy** [comment]
Hmm, Dart Web fails to compile, so we do not know whether this PR will work for the web or not. I will merge after it becomes green!

> Should i also increase the version number or will that be done after the merge?

No worries, I will do that

**Comment by MnlPhlp** [comment]
it compiles if i change the syn version in frb_codegen to 2. ... 
I just commented out some breaking changes to check compilation so the generator didn't work but it compiled.

Looks like we don't need many changes to use syn2 so i will try that tomorrow just to see if it works

Alternatively we would have to use another nightly compiler i think. But compilation is hidden in wasm-pack so i don't know how easy that would be

**Comment by MnlPhlp** [comment]
For some reason the stream tests using mirror types time out on wasm. Everything else seems to work.
The IOS tests also didn't run on this commit but I think they were unstable the whole time. Maybe we can just repeat the run and see if they work this time

**Comment by MnlPhlp** [comment]
The web test passed 🎉

**Comment by jrbpower** [comment]
how do i implement this?
error[E0277]: the trait bound `EventToUI: IntoIntoDart<_>` is not satisfied
   --> src/flutter.rs:294:20
    |
294 |             stream.add(EventToUI::Event("close".to_owned()));
    |                    ^^^ the trait `IntoIntoDart<_>` is not implemented for `EventToUI`
    |
    = help: the following other types implement trait `IntoIntoDart<D>`:
              <bool as IntoIntoDart<bool>>
              <i8 as IntoIntoDart<i8>>
              <i16 as IntoIntoDart<i16>>
              <i32 as IntoIntoDart<i32>>
              <i64 as IntoIntoDart<i64>>
              <usize as IntoIntoDart<usize>>
              <u8 as IntoIntoDart<u8>>
              <u16 as IntoIntoDart<u16>>
            and 23 others
note: required by a bound in `StreamSink::<T>::add`
   --> /home/jonathan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge-1.81.0/src/rust2dart.rs:139:12
    |
137 |     pub fn add<D: IntoDart>(&self, value: T) -> bool
    |            --- required by a bound in this associated function
138 |     where
139 |         T: IntoIntoDart<D>,
    |            ^^^^^^^^^^^^^^^ required by this bound in `StreamSink::<T>::add`
