### PR TITLE
Fix mirroring to support `Result` return type and `Option<T>` field

### LINKED ISSUE #895: [Bug] external types doesn't support the return type anyhow::Result<T>
### Describe the bug

When i want to use a Result as a return type, it can not generate properly on rust side. 

I changed just return type on `pure_dart` example like this 
[rust/srrust/src/api.rs line:555c/api.rs line:555
](https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/rust/src/api.rs#L554)
```rust
// This function can directly return an object of the external type ApplicationSettings because it has a mirror
pub fn get_app_settings() -> anyhow::Result<ApplicationSettings> {
    Ok(external_lib::get_app_settings())
}
```

image

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
flutter_rust_bridge/frb_example/pure_dart on  master [✘!?] took 36s 
❯ just
cd frb_codegen && cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
(cd frb_example/with_flutter && flutter pub get)
Running "flutter pub get" in with_flutter...                     1,523ms
cargo run --manifest-path frb_codegen/Cargo.toml -- -r frb_example/with_flutter/rust/src/api.rs -d frb_example/with_flutter/lib/bridge_generated.dart --dart-decl-output frb_example/with_flutter/lib/bridge_definitions.dart -c frb_example/with_flutter/ios/Runner/bridge_generated.h -c frb_example/with_flutter/macos/Runner/bridge_generated.h --dart-format-line-length 120 --wasm
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/flutter_rust_bridge_codegen -r frb_example/with_flutter/rust/src/api.rs -d frb_example/with_flutter/lib/bridge_generated.dart --dart-decl-output frb_example/with_flutter/lib/bridge_definitions.dart -c frb_example/with_flutter/ios/Runner/bridge_generated.h -c frb_example/with_flutter/macos/Runner/bridge_generated.h --dart-format-line-length 120 --wasm`
[2022-12-15T10:38:38Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module web (tried /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/web.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/web/mod.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/web.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/web/mod.rs, )
[2022-12-15T10:38:38Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module io (tried /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/io.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/io/mod.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/io.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/io/mod.rs, )
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (3 weeks ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0
[2022-12-15T10:38:39Z INFO  lib_flutter_rust_bridge_codegen] Picked config: Opts { rust_input_path: "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/api.rs", dart_output_path: "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_generated.dart", dart_decl_output_path: Some("/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_definitions.dart"), c_output_path: ["/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/ios/Runner/bridge_generated.h", "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/macos/Runner/bridge_generated.h"], rust_crate_dir: "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust", rust_output_path: "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated.rs", class_name: "FlutterRustBridgeExample", dart_format_line_length: 120, skip_add_mod_to_lib: false, llvm_path: ["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/msys64/mingw64"], llvm_compiler_opts: "", manifest_path: "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/Cargo.toml", dart_root: Some("/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter"), build_runner: true, block_index: BlockIndex(0), skip_deps_check: false, wasm_enabled: true, inline_rust: false }
[2022-12-15T10:38:39Z INFO  lib_flutter_rust_bridge_codegen] Phase: Parse source code to AST, then to IR
[2022-12-15T10:38:39Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module web (tried /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/web.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/web/mod.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/web.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/web/mod.rs, )
[2022-12-15T10:38:39Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module io (tried /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/io.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/io/mod.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/io.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/io/mod.rs, )
[2022-12-15T10:38:39Z INFO  lib_flutter_rust_bridge_codegen] Phase: Transform IR
[2022-12-15T10:38:39Z INFO  lib_flutter_rust_bridge_codegen] Phase: Generate Rust code
[2022-12-15T10:38:39Z INFO  lib_flutter_rust_bridge_codegen] Phase: Generate Dart code
[2022-12-15T10:38:39Z INFO  lib_flutter_rust_bridge_codegen] Phase: Generating Dart bindings for Rust
Running in Directory: '/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter'
Input Headers: [/tmp/.tmp8Pv5xr.h]
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: Generated declaration '_Dart_Handle' start's with '_' and therefore will be private.
Finished, Bindings generated in /tmp/.tmp6YQ3HG
[2022-12-15T10:38:43Z INFO  lib_flutter_rust_bridge_codegen] Phase: Running build_runner
[2022-12-15T10:38:43Z INFO  lib_flutter_rust_bridge_codegen] Phase: Formatting Dart code
Formatted /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_generated.dart
Formatted /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_definitions.dart
Formatted /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_generated.web.dart
Formatted /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_generated.io.dart
Formatted 4 files (4 changed) in 0.36 seconds.
[2022-12-15T10:38:43Z INFO  lib_flutter_rust_bridge_codegen] Success!
[2022-12-15T10:38:43Z INFO  flutter_rust_bridge_codegen] Now go and use it :)
cd frb_example/pure_dart/rust && cargo clean -p flutter_rust_bridge_example_single_block_test && cargo build
   Compiling flutter_rust_bridge_example_external v0.1.0 (/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/pure_dart/rust/external)
   Compiling flutter_rust_bridge_example_single_block_test v1.0.0 (/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/pure_dart/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 13.24s
cd frb_example/pure_dart_multi/rust && cargo clean -p flutter_rust_bridge_example_multi_blocks_test && cargo build
   Compiling flutter_rust_bridge_example_multi_blocks_test v1.0.0 (/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/pure_dart_multi/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 7.60s

flutter_rust_bridge/frb_example/pure_dart on  master took 29s 
❯ just
cd frb_codegen && cargo build
    Blocking waiting for file lock on build directory
    Finished dev [unoptimized + debuginfo] target(s) in 4.42s
(cd frb_example/with_flutter && flutter pub get)
Running "flutter pub get" in with_flutter...                     1,824ms
cargo run --manifest-path frb_codegen/Cargo.toml -- -r frb_example/with_flutter/rust/src/api.rs -d frb_example/with_flutter/lib/bridge_generated.dart --dart-decl-output frb_example/with_flutter/lib/bridge_definitions.dart -c frb_example/with_flutter/ios/Runner/bridge_generated.h -c frb_example/with_flutter/macos/Runner/bridge_generated.h --dart-format-line-length 120 --wasm
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/flutter_rust_bridge_codegen -r frb_example/with_flutter/rust/src/api.rs -d frb_example/with_flutter/lib/bridge_generated.dart --dart-decl-output frb_example/with_flutter/lib/bridge_definitions.dart -c frb_example/with_flutter/ios/Runner/bridge_generated.h -c frb_example/with_flutter/macos/Runner/bridge_generated.h --dart-format-line-length 120 --wasm`
[2022-12-15T10:39:49Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module web (tried /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/web.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/web/mod.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/web.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/web/mod.rs, )
[2022-12-15T10:39:49Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module io (tried /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/io.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/io/mod.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/io.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/io/mod.rs, )
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (3 weeks ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0
[2022-12-15T10:39:50Z INFO  lib_flutter_rust_bridge_codegen] Picked config: Opts { rust_input_path: "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/api.rs", dart_output_path: "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_generated.dart", dart_decl_output_path: Some("/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_definitions.dart"), c_output_path: ["/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/ios/Runner/bridge_generated.h", "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/macos/Runner/bridge_generated.h"], rust_crate_dir: "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust", rust_output_path: "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated.rs", class_name: "FlutterRustBridgeExample", dart_format_line_length: 120, skip_add_mod_to_lib: false, llvm_path: ["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/msys64/mingw64"], llvm_compiler_opts: "", manifest_path: "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/Cargo.toml", dart_root: Some("/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter"), build_runner: true, block_index: BlockIndex(0), skip_deps_check: false, wasm_enabled: true, inline_rust: false }
[2022-12-15T10:39:50Z INFO  lib_flutter_rust_bridge_codegen] Phase: Parse source code to AST, then to IR
[2022-12-15T10:39:51Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module web (tried /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/web.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/web/mod.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/web.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/web/mod.rs, )
[2022-12-15T10:39:51Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module io (tried /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/io.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/io/mod.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/io.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/io/mod.rs, )
[2022-12-15T10:39:51Z INFO  lib_flutter_rust_bridge_codegen] Phase: Transform IR
[2022-12-15T10:39:51Z INFO  lib_flutter_rust_bridge_codegen] Phase: Generate Rust code
[2022-12-15T10:39:51Z INFO  lib_flutter_rust_bridge_codegen] Phase: Generate Dart code
[2022-12-15T10:39:51Z INFO  lib_flutter_rust_bridge_codegen] Phase: Generating Dart bindings for Rust
Running in Directory: '/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter'
Input Headers: [/tmp/.tmpvuFgL7.h]
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: Generated declaration '_Dart_Handle' start's with '_' and therefore will be private.
Finished, Bindings generated in /tmp/.tmpd58Tid
[2022-12-15T10:39:54Z INFO  lib_flutter_rust_bridge_codegen] Phase: Running build_runner
[2022-12-15T10:39:54Z INFO  lib_flutter_rust_bridge_codegen] Phase: Formatting Dart code
Formatted /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_generated.dart
Formatted /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_definitions.dart
Formatted /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_generated.web.dart
Formatted /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_generated.io.dart
Formatted 4 files (4 changed) in 0.34 seconds.
[2022-12-15T10:39:54Z INFO  lib_flutter_rust_bridge_codegen] Success!
[2022-12-15T10:39:54Z INFO  flutter_rust_bridge_codegen] Now go and use it :)
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Generated binding code

_No response_

### OS

Arch linux

### Version of `flutter_rust_bridge_codegen`

1.54

### Flutter info

_No response_

### Version of `clang++`

_No response_

### Version of `ffigen`

_No response_

### Additional context

_No response_

### LINKED ISSUE #897: [Bug] mirroring not working when struct has another optional struct
### Describe the bug

When your struct has another optional struct, it gives `cannot be dereferenced` error.
```rust
pub struct Parent {
       pub child: Option<Child>
}
pub struct Child {
       pub name: String
}
```
image

I changed only pure_dart example 
https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/rust/external/src/lib.rs
```diff
diff --git a/frb_example/pure_dart/rust/external/src/lib.rs b/frb_example/pure_dart/rust/external/src/lib.rs
index c44feb76..b97c4adf 100644
--- a/frb_example/pure_dart/rust/external/src/lib.rs
+++ b/frb_example/pure_dart/rust/external/src/lib.rs
@@ -6,6 +6,12 @@ pub struct ApplicationSettings {
     pub version: String,
     pub mode: ApplicationMode,
     pub env: Box<ApplicationEnv>,
+    pub child: Option<ChildApplicationSetting>,
+}
+
+#[derive(Debug, Clone)]
+pub struct ChildApplicationSetting {
+    pub name: String,
 }
 
 #[derive(Debug, Clone)]
@@ -52,6 +58,7 @@ impl ApplicationSettings {
                     .map(|(k, v)| ApplicationEnvVar(k.into(), v))
                     .collect(),
             }),
+            child: None,
         }
     }
 }
 ```
 
https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/rust/src/api.rs
 ```diff
 diff --git a/frb_example/pure_dart/rust/src/api.rs b/frb_example/pure_dart/rust/src/api.rs
index d5b617a6..ba7e4c0c 100644
--- a/frb_example/pure_dart/rust/src/api.rs
+++ b/frb_example/pure_dart/rust/src/api.rs
@@ -526,7 +526,7 @@ pub fn use_imported_enum(my_enum: MyEnum) -> bool {
 // To use an external type with mirroring, it MUST be imported publicly (aka. re-export)
 pub use external_lib::{
     ApplicationEnv, ApplicationEnvVar, ApplicationMessage, ApplicationMode, ApplicationSettings,
-    Numbers, Sequences,
+    ChildApplicationSetting, Numbers, Sequences,
 };
 
 // To mirror an external struct, you need to define a placeholder type with the same definition
@@ -536,6 +536,12 @@ pub struct _ApplicationSettings {
     pub version: String,
     pub mode: ApplicationMode,
     pub env: Box<ApplicationEnv>,
+    pub child: Option<ChildApplicationSetting>,
+}
+
+#[frb(mirror(ChildApplicationSetting))]
+pub struct _ChildApplicationSetting {
+    pub name: String,
 }
 
 #[frb(mirror(ApplicationMode))]
 ```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
cd frb_codegen && cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
(cd frb_example/with_flutter && flutter pub get)
Running "flutter pub get" in with_flutter...                     1,282ms
cargo run --manifest-path frb_codegen/Cargo.toml -- -r frb_example/with_flutter/rust/src/api.rs -d frb_example/with_flutter/lib/bridge_generated.dart --dart-decl-output frb_example/with_flutter/lib/bridge_definitions.dart -c frb_example/with_flutter/ios/Runner/bridge_generated.h -c frb_example/with_flutter/macos/Runner/bridge_generated.h --dart-format-line-length 120 --wasm
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/flutter_rust_bridge_codegen -r frb_example/with_flutter/rust/src/api.rs -d frb_example/with_flutter/lib/bridge_generated.dart --dart-decl-output frb_example/with_flutter/lib/bridge_definitions.dart -c frb_example/with_flutter/ios/Runner/bridge_generated.h -c frb_example/with_flutter/macos/Runner/bridge_generated.h --dart-format-line-length 120 --wasm`
[2022-12-15T11:43:46Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module web (tried /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/web.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/web/mod.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/web.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/web/mod.rs, )
[2022-12-15T11:43:46Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module io (tried /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/io.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/io/mod.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/io.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/io/mod.rs, )
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (3 weeks ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0
[2022-12-15T11:43:47Z INFO  lib_flutter_rust_bridge_codegen] Picked config: Opts { rust_input_path: "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/api.rs", dart_output_path: "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_generated.dart", dart_decl_output_path: Some("/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_definitions.dart"), c_output_path: ["/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/ios/Runner/bridge_generated.h", "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/macos/Runner/bridge_generated.h"], rust_crate_dir: "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust", rust_output_path: "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated.rs", class_name: "FlutterRustBridgeExample", dart_format_line_length: 120, skip_add_mod_to_lib: false, llvm_path: ["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/msys64/mingw64"], llvm_compiler_opts: "", manifest_path: "/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/Cargo.toml", dart_root: Some("/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter"), build_runner: true, block_index: BlockIndex(0), skip_deps_check: false, wasm_enabled: true, inline_rust: false }
[2022-12-15T11:43:47Z INFO  lib_flutter_rust_bridge_codegen] Phase: Parse source code to AST, then to IR
[2022-12-15T11:43:47Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module web (tried /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/web.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/web/mod.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/web.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/web/mod.rs, )
[2022-12-15T11:43:47Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module io (tried /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/io.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/io/mod.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/io.rs, /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/rust/src/bridge_generated/io/mod.rs, )
[2022-12-15T11:43:47Z INFO  lib_flutter_rust_bridge_codegen] Phase: Transform IR
[2022-12-15T11:43:47Z INFO  lib_flutter_rust_bridge_codegen] Phase: Generate Rust code
[2022-12-15T11:43:47Z INFO  lib_flutter_rust_bridge_codegen] Phase: Generate Dart code
[2022-12-15T11:43:47Z INFO  lib_flutter_rust_bridge_codegen] Phase: Generating Dart bindings for Rust
Running in Directory: '/home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter'
Input Headers: [/tmp/.tmpub9YFD.h]
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: No definition found for declaration - (Cursor) spelling: _Dart_Handle, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct _Dart_Handle, usr: c:@S@_Dart_Handle
[WARNING]: Generated declaration '_Dart_Handle' start's with '_' and therefore will be private.
Finished, Bindings generated in /tmp/.tmpidyEe3
[2022-12-15T11:43:51Z INFO  lib_flutter_rust_bridge_codegen] Phase: Running build_runner
[2022-12-15T11:43:51Z INFO  lib_flutter_rust_bridge_codegen] Phase: Formatting Dart code
Formatted /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_generated.dart
Formatted /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_definitions.dart
Formatted /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_generated.web.dart
Formatted /home/cengiz/StudioProjects/flutter_rust_bridge/frb_example/with_flutter/lib/bridge_generated.io.dart
Formatted 4 files (4 changed) in 0.30 seconds.
[2022-12-15T11:43:51Z INFO  lib_flutter_rust_bridge_codegen] Success!
[2022-12-15T11:43:51Z INFO  flutter_rust_bridge_codegen] Now go and use it :)
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Generated binding code

_No response_

### OS

Archlinux

### Version of `flutter_rust_bridge_codegen`

1.54

### Flutter info

_No response_

### Version of `clang++`

_No response_

### Version of `ffigen`

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by codercengiz**
Fixes #895
Fixes #897 

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [x] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- [x] The code generator is run and the code is formatted (e.g. via `just refresh_all`).
- [ ] If this PR adds/changes features, documentations (in the `./book` folder) are updated.
- [x] CI is passing.

## Remark for PR creator

* New contributors will be blocked by GitHub from running CI, but you can use [a trick](https://github.com/fzyzcjy/flutter_rust_bridge/pull/663#discussion_r962150638) to workaround this, and verify your code using CI by yourself.
* If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

### CODE REVIEW

File: frb_codegen/src/generator/rust/ty_optional.rs [hunk 1]
```diff
@@ -34,19 +34,18 @@ impl TypeRustGeneratorTrait for TypeOptionalGenerator<'_> {
...
             self.context.config,
         );
         let obj = match inner.wrapper_struct() {
-            Some(wrapper) => format!(
-                "{}.map(|v| {}({}))",
-                obj,
-                wrapper,
-                inner.self_access("v".to_owned())
-            ),
+            Some(wrapper) => format!("{}.map(|v| {}(v))", obj, wrapper,),
```
Comment (codercengiz) [inline frb_codegen/src/generator/rust/ty_optional.rs:48]: As far as I understand, an architecture has been created so that the inner type of optional field is always `IrTypeBoxed`. (I couldn't quite understand why.) Here, too, if we use `inner.self_access("v".to_owned())`, since it will go to `self_access` in `TypeBoxedGenerator`, the dereferenced value `*v` was returned from there, which gave the error that the external struct could not be dereferenced.

For now, I removed the parameter `inner.self_access("v".to_owned())` and then I've added a bit of a hacky method here, as it only covers mirrored optional fields.

Comment (fzyzcjy) [reply frb_codegen/src/generator/rust/ty_optional.rs:48]: > I couldn't quite understand why

Well, for simplicity? Because `Optional<Boxed<sth>>` can be translated to "nullable pointer", while `Optional<SthThatIsNotABox>` is harder to translate (maybe also forcefully translate to a nullable pointer?). But anyway, feel free to fix this problem!

File: frb_codegen/src/generator/rust/ty_struct.rs [hunk 2]
```diff
@@ -108,9 +108,16 @@ impl TypeRustGeneratorTrait for TypeStructRefGenerator<'_> {
         src.wrapper_name.as_ref().cloned()
     }
 
-    fn wrap_obj(&self, obj: String) -> String {
+    fn wrap_obj(&self, obj: String, wired_fallible_func: bool) -> String {
         match self.wrapper_struct() {
-            Some(wrapper) => format!("{}({})", wrapper, obj),
+            Some(wrapper) => {
+                if wired_fallible_func {
+                    format!("{}.map_or_else(|e| Err(e), |v| Ok({}(v)))", obj, wrapper)
```
Comment (fzyzcjy) [inline frb_codegen/src/generator/rust/ty_struct.rs:115]: btw, does not briefer syntax work: `wrapper(obj?)`, i.e. the `?`

**Review by fzyzcjy — COMMENTED** [review]
LGTM, only nits :)

**Review by fzyzcjy — APPROVED** [review]

**Comment by fzyzcjy** [comment]
@all-contributors please add codercengiz for code
